### ISSUE TITLE
There are no calendars to import in windows version

### ISSUE THREAD

**Issue by mschol02** [bardsoftware/ganttproject#1176]
If i choose Properties "$Project Calender" there are no Calendars to choose. Only two entries: "Nothing" and "user defined", but no country calendars.

in ..\plugins\net.sourceforge.ganttproject\data\resources\calendar\  the i18n_... files are existing.

In the Mac-OS Version, the calendars will be displayed correctly!

(Both german version)

**Comment by dbarashev** [comment]
Thanks for reporting. It seems that space in the application folder name causes this issue. Try installing GanttProject in a folder with no spaces in the path.

WARNING: Illegal character in path at index 16: file:/C:/Program Files (x86)/GanttProject-2.7/plugins/net.sourceforge.ganttproject/data/resources/calendar
at net.sourceforge.ganttproject.gui.projectwizard.WeekendConfigurationPage.<init>(WeekendConfigurationPage.java:154)
	at net.sourceforge.ganttproject.gui.options.WeekendsSettingsPanel.initialize(WeekendsSettingsPanel.java:92)
	at net.sourceforge.ganttproject.gui.options.ProjectCalendarOptionPageProvider.buildPageComponent(ProjectCalendarOptionPageProvider.java:88)
	at net.sourceforge.ganttproject.gui.options.OptionPageProviderPanel.getComponent(OptionPageProviderPanel.java:47)
	at net.sourceforge.ganttproject.gui.options.SettingsDialog2.getListItems(SettingsDialog2.java:80)
	at net.sourceforge.ganttproject.gui.options.SettingsDialog2.getPages(SettingsDialog2.java:61)
	at net.sourceforge.ganttproject.gui.options.SettingsDialog2.<init>(SettingsDialog2.java:44)
	at net.sourceforge.ganttproject.action.project.ProjectPropertiesAction$1.run(ProjectPropertiesAction.java:45)
	at net.sourceforge.ganttproject.undo.UndoableEditImpl.<init>(UndoableEditImpl.java:47)
	at net.sourceforge.ganttproject.undo.UndoManagerImpl.undoableEdit(UndoManagerImpl.java:74)
	at net.sourceforge.ganttproject.action.project.ProjectPropertiesAction.actionPerformed(ProjectPropertiesAction.java:42)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Sou

**Comment by xs133** [comment]
The same issue happens on my system too . My application folder name is the default one "c:GanttProject-2.7"
