### ISSUE TITLE
Error Can't open document : No enum constant

### ISSUE THREAD

**Issue by Mistralain** [bardsoftware/ganttproject#1405]
Caused by: java.io.IOException: No enum constant biz.ganttproject.core.calendar.CalendarEvent.Type.ate-con

I can open  the other document.

Can you help me, thanks,
Alain

**Comment by dbarashev** [comment]
Please post the full log and attach your project file, if you can share it.

**Comment by Mistralain** [comment]
I mail you to contact@ganttproject.biz the full log and the project file.
 
The end of the log:
AVERTISSEMENT: No enum constant biz.ganttproject.core.calendar.CalendarEvent.Type.ate-con
java.lang.IllegalArgumentException: No enum constant biz.ganttproject.core.calendar.CalendarEvent.Type.ate-con
	at java.lang.Enum.valueOf(Unknown Source)
	at biz.ganttproject.core.calendar.CalendarEvent$Type.valueOf(CalendarEvent.java:39)
	at net.sourceforge.ganttproject.parser.HolidayTagHandler.loadHoliday(HolidayTagHandler.java:117)
	at net.sourceforge.ganttproject.parser.HolidayTagHandler.endElement(HolidayTagHandler.java:71)
	at net.sourceforge.ganttproject.io.XmlParser.endElement(XmlParser.java:88)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at net.sourceforge.ganttproject.io.XmlParser.parse(XmlParser.java:110)
	at net.sourceforge.ganttproject.io.GanttXMLOpen.doLoad(GanttXMLOpen.java:102)
	at net.sourceforge.ganttproject.io.GanttXMLOpen.load(GanttXMLOpen.java:96)
	at net.sourceforge.ganttproject.document.ProxyDocument$ParsingState.enter(ProxyDocument.java:360)
	at net.sourceforge.ganttproject.document.ProxyDocument.read(ProxyDocument.java:178)
	at net.sourceforge.ganttproject.GanttProject.open(GanttProject.java:687)
	at net.sourceforge.ganttproject.gui.ProjectOpenStrategy.openFileAsIs(ProjectOpenStrategy.java:119)
	at net.sourceforge.ganttproject.gui.ProjectUIFacadeImpl.openProject(ProjectUIFacadeImpl.java:248)
	at net.sourceforge.ganttproject.gui.ProjectUIFacadeImpl.openProject(ProjectUIFacadeImpl.java:238)
	at net.sourceforge.ganttproject.action.project.OpenProjectAction.actionPerformed(OpenProjectAction.java:58)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

avr. 24, 2017 6:55:29 PM net.sourceforge.ganttproject.GPLogger logToLogger
AVERTISSEMENT: Can't open document net.sourceforge.ganttproject.document.ProxyDocument@56819023
net.sourceforge.ganttproject.document.Document$DocumentException: Can't open document net.sourceforge.ganttproject.document.ProxyDocument@56819023
	at net.sourceforge.ganttproject.gui.ProjectUIFacadeImpl.openProject(ProjectUIFacadeImpl.java:253)
	at net.sourceforge.ganttproject.gui.ProjectUIFacadeImpl.openProject(ProjectUIFacadeImpl.java:238)
	at net.sourceforge.ganttproject.action.project.OpenProjectAction.actionPerformed(OpenProjectAction.java:58)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: No enum constant biz.ganttproject.core.calendar.CalendarEvent.Type.ate-con
	at net.sourceforge.ganttproject.io.XmlParser.parse(XmlParser.java:125)
	at net.sourceforge.ganttproject.io.GanttXMLOpen.doLoad(GanttXMLOpen.java:102)
	at net.sourceforge.ganttproject.io.GanttXMLOpen.load(GanttXMLOpen.java:96)
	at net.sourceforge.ganttproject.document.ProxyDocument$ParsingState.enter(ProxyDocument.java:360)
	at net.sourceforge.ganttproject.document.ProxyDocument.read(ProxyDocument.java:178)
	at net.sourceforge.ganttproject.GanttProject.open(GanttProject.java:687)
	at net.sourceforge.ganttproject.gui.ProjectOpenStrategy.openFileAsIs(ProjectOpenStrategy.java:119)
	at net.sourceforge.ganttproject.gui.ProjectUIFacadeImpl.openProject(ProjectUIFacadeImpl.java:248)
	... 40 more

**Comment by dbarashev** [comment]
Related report: https://help.ganttproject.biz/t/file-suddenly-unusable-no-enum-constant/755
