### ISSUE TITLE
Export to MPX file error

### ISSUE THREAD

**Issue by startrooper3000** [bardsoftware/ganttproject#1411]
Hello,

I imported a MS Project file to Ganttproject, worked on it, then went to export it for colleagues to view with MS Project, but I received an error message.  See below.  I did try the fix offered in Issue #1390, deleting the unnecessary custom columns, resaving the file, closing the program, reloading, then exporting.  No luck.  Thoughts?

May 14, 2017 12:41:49 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: Export failure. Failed subtask: Export project
java.lang.RuntimeException: Export failure. Failed subtask: Export project
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:167)
	at org.bardsoftware.impl.eclipsito.JobManagerImpl$GroupWorker.run(JobManagerImpl.java:163)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at net.sf.mpxj.CustomFieldContainer.registerAlias(CustomFieldContainer.java:109)
	at net.sf.mpxj.CustomField.setAlias(CustomField.java:93)
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.exportResources(ProjectFileExporter.java:309)
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.run(ProjectFileExporter.java:72)
	at biz.ganttproject.impex.msproject2.ExporterToMsProjectFile$2.run(ExporterToMsProjectFile.java:118)
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:165)
	... 2 more

May 14, 2017 12:42:28 PM net.sourceforge.ganttproject.GPLogger log
INFO: [ProgressMonitorImpl] begin Task: name=Running export
May 14, 2017 12:42:28 PM net.sourceforge.ganttproject.GPLogger log
INFO: [ProgressMonitorImpl] begin subTask: name=Export project
May 14, 2017 12:42:28 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: Export failure. Failed subtask: Export project
java.lang.RuntimeException: Export failure. Failed subtask: Export project
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:167)
	at org.bardsoftware.impl.eclipsito.JobManagerImpl$GroupWorker.run(JobManagerImpl.java:163)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at net.sf.mpxj.CustomFieldContainer.registerAlias(CustomFieldContainer.java:109)
	at net.sf.mpxj.CustomField.setAlias(CustomField.java:93)
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.exportResources(ProjectFileExporter.java:309)
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.run(ProjectFileExporter.java:72)
	at biz.ganttproject.impex.msproject2.ExporterToMsProjectFile$2.run(ExporterToMsProjectFile.java:118)
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:165)
	... 2 more

May 14, 2017 12:45:01 PM net.sourceforge.ganttproject.GPLogger log
INFO: [ProgressMonitorImpl] begin Task: name=Running export
May 14, 2017 12:45:01 PM net.sourceforge.ganttproject.GPLogger log
INFO: [ProgressMonitorImpl] begin subTask: name=Export project
May 14, 2017 12:45:01 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: Export failure. Failed subtask: Export project
java.lang.RuntimeException: Export failure. Failed subtask: Export project
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:167)
	at org.bardsoftware.impl.eclipsito.JobManagerImpl$GroupWorker.run(JobManagerImpl.java:163)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at net.sf.mpxj.CustomFieldContainer.registerAlias(CustomFieldContainer.java:109)
	at net.sf.mpxj.CustomField.setAlias(CustomField.java:93)
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.exportResources(ProjectFileExporter.java:309)
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.run(ProjectFileExporter.java:72)
	at biz.ganttproject.impex.msproject2.ExporterToMsProjectFile$2.run(ExporterToMsProjectFile.java:118)
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:165)
	... 2 more

May 14, 2017 12:50:19 PM net.sourceforge.ganttproject.GPLogger log
INFO: [ProgressMonitorImpl] begin Task: name=Running export
May 14, 2017 12:50:19 PM net.sourceforge.ganttproject.GPLogger log
INFO: [ProgressMonitorImpl] begin subTask: name=Export project
May 14, 2017 12:50:19 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: Export failure. Failed subtask: Export project
java.lang.RuntimeException: Export failure. Failed subtask: Export project
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:167)
	at org.bardsoftware.impl.eclipsito.JobManagerImpl$GroupWorker.run(JobManagerImpl.java:163)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at net.sf.mpxj.CustomFieldContainer.registerAlias(CustomFieldContainer.java:109)
	at net.sf.mpxj.CustomField.setAlias(CustomField.java:93)
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.exportResources(ProjectFileExporter.java:309)
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.run(ProjectFileExporter.java:72)
	at biz.ganttproject.impex.msproject2.ExporterToMsProjectFile$2.run(ExporterToMsProjectFile.java:118)
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:165)
	... 2 more

**Comment by dbarashev** [comment]
Duplicates #1390

**Comment by dbarashev** [comment]
This is exactly what is addressed in #1390. Please make sure that you removed resource custom columns as well.
