### ISSUE TITLE
Error if checking "earliest begin" without specifying the date 

### ISSUE THREAD

**Issue by aschramek** [bardsoftware/ganttproject#1413]
I am using the german version so I am not sure if my translation correctly identifies the items in the english version. 

GIVEN I create a new task ("Vorgang") 
WHEN in the task attributes ("Eigenschaften") I click on the checkbox for earliest begin ("frühester beginn")
AND I click on OK
THEN /* see below */ (I guess the date field for "earliest begin" in this case should also be mandatory)

GanttProject 2.8.5 Pilsen (build 2179)
Settings file:
	location: C:\Users\alexa\.ganttproject
	size:4233
	is readable: true
java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject-2.8
java.home: C:\Program Files (x86)\Java\jre1.8.0_101
java.ext.dirs: C:\Program Files (x86)\Java\jre1.8.0_101\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
java.io.tmpdir: C:\Users\alexa\AppData\Local\Temp\
java.runtime.version: 1.8.0_101-b13
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) Client VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.101-b13
os.arch: x86
os.name: Windows 10
os.version: 10.0
sun.java.command: org.bardsoftware.eclipsito.Boot ganttproject-eclipsito-config.xml -log true
user.country: AT
user.dir: C:\Program Files (x86)\GanttProject-2.8
user.home: C:\Users\alexa
user.language: de
user.timezone: Europe/Berlin

Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
8. finalizing...
Main frame created
Splash closed
Resizing window...
ATION: Bounds stored in the  options: java.awt.Rectangle[x=-11,y=-11,width=1942,height=1042]
Mai 24, 2017 8:44:31 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after setVisible: java.awt.Rectangle[x=-11,y=-11,width=1932,height=1042]
Mai 24, 2017 8:44:31 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Starting RSS check...
Mai 24, 2017 8:44:32 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after opening: java.awt.Rectangle[x=-11,y=-11,width=1932,height=1042]
Mai 24, 2017 8:44:32 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds stored in the  options: java.awt.Rectangle[x=-11,y=-11,width=1942,height=1042]
Mai 24, 2017 8:44:33 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: RSS check finished
Mai 24, 2017 8:44:38 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories...
Mai 24, 2017 8:44:38 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:\Program Files (x86)\Java\jre1.8.0_101/lib/fonts
Mai 24, 2017 8:44:38 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:/windows/fonts
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.GPLogger debug
FEIN: Scheduling node Vorgang_0
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.GPLogger debug
FEIN: Scheduling node Vorgang_0
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.GPLogger debug
FEIN: .. #incoming edges=0
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.GPLogger debug
FEIN: .. #incoming edges=0
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.GPLogger debug
FEIN: ..Ranges: start=(-??+?) end=(-??+?) weakStart=(-??+?) weakEnd=(-??+?)
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.GPLogger debug
FEIN: ..Ranges: start=(-??+?) end=(-??+?) weakStart=(-??+?) weakEnd=(-??+?)
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.GPLogger debug
FEIN: ..Subtasks span=[Wed May 24 00:00:00 UTC 2017?Thu May 25 00:00:00 UTC 2017]
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.GPLogger debug
FEIN: ..Subtasks span=[Wed May 24 00:00:00 UTC 2017?Thu May 25 00:00:00 UTC 2017]
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.GPLogger debug
FEIN: .. finally, start range=(-??+?)
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.GPLogger debug
FEIN: .. finally, start range=(-??+?)
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.task.algorithm.CriticalPathAlgorithmImpl$Processor calculateLatestDates
FEIN: Calculating latest dates for:Vorgang_0
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.task.algorithm.CriticalPathAlgorithmImpl$Processor calculateLatestDates
FEIN: Calculating latest dates for:Vorgang_0
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.task.algorithm.CriticalPathAlgorithmImpl$Processor findLatestFinishTime
FEIN: latest finish time=Thu May 25 00:00:00 UTC 2017 (defined by:null)
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.task.algorithm.CriticalPathAlgorithmImpl$Processor findLatestFinishTime
FEIN: latest finish time=Thu May 25 00:00:00 UTC 2017 (defined by:null)
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.task.algorithm.CriticalPathAlgorithmImpl$Processor calculateLatestDates
FEIN: latest start date=Wed May 24 00:00:00 UTC 2017
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.task.algorithm.CriticalPathAlgorithmImpl$Processor calculateLatestDates
FEIN: latest start date=Wed May 24 00:00:00 UTC 2017
Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.task.algorithm.CriticalPathAlgorithmImpl$Processor processQueue
FEIN: 

Node=Vorgang_0 is critical

Mai 24, 2017 8:44:39 PM net.sourceforge.ganttproject.task.algorithm.CriticalPathAlgorithmImpl$Processor processQueue
FEIN: 

Node=Vorgang_0 is critical

Mai 24, 2017 8:44:45 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/usr/share/fonts/truetype
Mai 24, 2017 8:44:45 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /usr/share/fonts/truetype is not readable
Mai 24, 2017 8:44:45 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/System/Library/Fonts
Mai 24, 2017 8:44:45 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /System/Library/Fonts is not readable
Mai 24, 2017 8:44:45 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/C:/Program Files (x86)/GanttProject-2.8/plugins-2.8.5/org.ganttproject.impex.htmlpdf/resource/fonts
Mai 24, 2017 8:44:45 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories completed
Mai 24, 2017 8:44:51 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNUNG: null
java.lang.NullPointerException
	at net.sourceforge.ganttproject.task.TaskImpl.setThirdDate(TaskImpl.java:995)
	at net.sourceforge.ganttproject.task.TaskImpl$MutatorImpl.commit(TaskImpl.java:635)
	at net.sourceforge.ganttproject.gui.GanttTaskPropertiesBean.applySettings(GanttTaskPropertiesBean.java:431)
	at net.sourceforge.ganttproject.gui.GanttDialogProperties$1$1.run(GanttDialogProperties.java:50)
	at net.sourceforge.ganttproject.undo.UndoableEditImpl.<init>(UndoableEditImpl.java:48)
	at net.sourceforge.ganttproject.undo.UndoManagerImpl.undoableEdit(UndoManagerImpl.java:74)
	at net.sourceforge.ganttproject.gui.GanttDialogProperties$1.actionPerformed(GanttDialogProperties.java:47)
	at net.sourceforge.ganttproject.DialogBuilder$1$1.run(DialogBuilder.java:208)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at net.sourceforge.ganttproject.DialogBuilder$DialogImpl.show(DialogBuilder.java:148)
	at net.sourceforge.ganttproject.gui.GanttDialogProperties.show(GanttDialogProperties.java:73)
	at net.sourceforge.ganttproject.action.task.TaskPropertiesAction.run(TaskPropertiesAction.java:66)
	at net.sourceforge.ganttproject.action.task.TaskActionBase$2.run(TaskActionBase.java:83)
	at net.sourceforge.ganttproject.undo.UndoableEditImpl.<init>(UndoableEditImpl.java:48)
	at net.sourceforge.ganttproject.undo.UndoManagerImpl.undoableEdit(UndoManagerImpl.java:74)
	at net.sourceforge.ganttproject.action.task.TaskActionBase.actionPerformed(TaskActionBase.java:79)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by dbarashev** [comment]
Thanks for reporting!
