### ISSUE TITLE
Ganttproject error - Help Please 

### ISSUE THREAD

**Issue by musa86** [bardsoftware/ganttproject#1417]
I have a Projectlibre file (.pod) , i can't open it with ganttproject.
Is it possible to be opened and how can I open it
Can't open document net.sourceforge.ganttproject.document.ProxyDocument@ff7df8 Invalid byte 1 of 1-byte UTF-8 sequence.

I am using Windows 7 Prof. with latest Java v. 
Any help would be appreciated 

C:\Users\********\ganttproject.log

GanttProject 2.8.5 Pilsen (build 2179)
Settings file:
	location: C:\Users\*******\.ganttproject
	size:4012
	is readable: true
java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject-2.8
java.home: C:\Program Files (x86)\Java\jre1.8.0_131
java.ext.dirs: C:\Program Files (x86)\Java\jre1.8.0_131\lib\ext;C:\Windows\Sun\Java\lib\ext
java.io.tmpdir: C:\Users\********\AppData\Local\Temp\
java.runtime.version: 1.8.0_131-b11
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) Client VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.131-b11
os.arch: x86
os.name: Windows 7
os.version: 6.1
sun.java.command: org.bardsoftware.eclipsito.Boot ganttproject-eclipsito-config.xml -log true C:\Users\********\Desktop\2019 DP Rear Axle  Vent SP32735.pod
user.country: US
user.dir: C:\Program Files (x86)\GanttProject-2.8
user.home: C:\Users\****
user.language: en
user.timezone: America/New_York

Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
8. finalizing...
Main frame created
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
Splash closed
Resizing window...
nono editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
ent$DocumentException: Can't open document net.sourceforge.ganttproject.document.ProxyDocument@1cd2b88
	at net.sourceforge.ganttproject.gui.ProjectUIFacadeImpl.openProject(ProjectUIFacadeImpl.java:253)
	at net.sourceforge.ganttproject.GanttProject$14.run(GanttProject.java:710)
	at net.sourceforge.ganttproject.undo.UndoableEditImpl.<init>(UndoableEditImpl.java:48)
	at net.sourceforge.ganttproject.undo.UndoManagerImpl.undoableEdit(UndoManagerImpl.java:74)
	at net.sourceforge.ganttproject.GanttProject.openStartupDocument(GanttProject.java:706)
	at net.sourceforge.ganttproject.GanttProject$16.run(GanttProject.java:949)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.arrangeCapacity(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipString(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at net.sourceforge.ganttproject.io.XmlParser.parse(XmlParser.java:110)
	at net.sourceforge.ganttproject.io.GanttXMLOpen.doLoad(GanttXMLOpen.java:102)
	at net.sourceforge.ganttproject.io.GanttXMLOpen.load(GanttXMLOpen.java:96)
	at net.sourceforge.ganttproject.document.ProxyDocument$ParsingState.enter(ProxyDocument.java:360)
	at net.sourceforge.ganttproject.document.ProxyDocument.read(ProxyDocument.java:178)
	at net.sourceforge.ganttproject.GanttProject.open(GanttProject.java:687)
	at net.sourceforge.ganttproject.gui.ProjectOpenStrategy.openFileAsIs(ProjectOpenStrategy.java:119)
	at net.sourceforge.ganttproject.gui.ProjectUIFacadeImpl.openProject(ProjectUIFacadeImpl.java:248)
	... 19 more

Jun 01, 2017 8:52:52 AM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds after setVisible: java.awt.Rectangle[x=328,y=46,width=1636,height=777]
Jun 01, 2017 8:52:52 AM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds after opening: java.awt.Rectangle[x=328,y=46,width=1636,height=777]
Jun 01, 2017 8:52:52 AM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds stored in the  options: java.awt.Rectangle[x=328,y=46,width=1636,height=777]
Jun 01, 2017 8:52:59 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFO: Scanning font directories...
Jun 01, 2017 8:52:59 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=C:\Program Files (x86)\Java\jre1.8.0_131/lib/fonts
Jun 01, 2017 8:53:00 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=C:/windows/fonts
Jun 01, 2017 8:53:03 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/usr/share/fonts/truetype
Jun 01, 2017 8:53:03 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: directory /usr/share/fonts/truetype is not readable
Jun 01, 2017 8:53:03 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/System/Library/Fonts
Jun 01, 2017 8:53:03 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: directory /System/Library/Fonts is not readable
Jun 01, 2017 8:53:03 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/C:/Program Files (x86)/GanttProject-2.8/plugins-2.8.5/org.ganttproject.impex.htmlpdf/resource/fonts
Jun 01, 2017 8:53:03 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFO: Scanning font directories completed
Jun 01, 2017 8:53:26 AM net.sourceforge.ganttproject.GPLogger log
INFO: [GanttOptions] save(): finished!!
Jun 01, 2017 8:53:26 AM net.sourceforge.ganttproject.GPLogger log
INFO: Main window has closed
Jun 01, 2017 8:53:26 AM net.sourceforge.ganttproject.GPLogger log
INFO: Program terminated

**Comment by dbarashev** [comment]
GanttProject can't open ProjectLibre's files, sorry. You may try exporting from ProjectLibre to MS Project and importing the result into GanttProject.
