### ISSUE TITLE
Hitting cmd+N for new project crashes GanttProject

### ISSUE THREAD

**Issue by ryanthara** [bardsoftware/ganttproject#1437]
Hitting cmd+N for new project crashes GanttProject Pilsen 2179 immediately.

**Comment by dbarashev** [comment]
It works fine on my Mac.
Please run GanttProject from the terminal (provided that dmg file is mounted as "GanttProject 2.8.5", this command is supposed to start GP: 
```
/Volumes/GanttProject\ 2.8.5/GanttProject.app/Contents/MacOS/JavaAppLauncher
```

and post the contents of terminal output and `ganttproject.log` file (it sits in your home folder)

**Comment by ryanthara** [comment]
When I run the command from the terminal, the crash could not be repeated. Good message for me.

Here are the log file from the Time Machine backup after the crash.

`GanttProject 2.8.5 Pilsen (build 2179)
Settings file:
	location: /Users/sebastian/.ganttproject
	size:4096
	is readable: true
java.class.path: /Applications/GanttProject.app/Contents/Java/Classes:/Applications/GanttProject.app/Contents/Java/eclipsito.jar
java.home: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
java.ext.dirs: /Users/sebastian/Library/Java/Extensions:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
java.io.tmpdir: /var/folders/tw/g0f41qvx1b1_7h8k98s2nsz00000gn/T/
java.runtime.version: 1.8.0_131-b11
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.131-b11
os.arch: x86_64
os.name: Mac OS X
os.version: 10.12.5
sun.java.command: org.bardsoftware.eclipsito.Boot -app net.sourceforge.ganttproject.GanttProject -plugins-dir /Applications/GanttProject.app/Contents/Java/plugins-2.8.5 -log true
user.country: DE
user.dir: /Users/sebastian
user.home: /Users/sebastian
user.language: de
user.timezone: Europe/Paris

Jul 04, 2017 8:57:13 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Options file:/Users/sebastian/.ganttproject
Jul 04, 2017 8:57:14 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Waiting until main window closes
Jul 04, 2017 8:57:14 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
Jul 04, 2017 8:57:17 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds stored in the  options: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
8. finalizing...
Main frame created
Jul 04, 2017 8:57:17 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after setVisible: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Jul 04, 2017 8:57:17 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Starting RSS check...
Splash closed
Resizing window...
Jul 04, 2017 8:57:18 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after opening: java.awt.Rectangle[x=0,y=28,width=1431,height=868]
Jul 04, 2017 8:57:18 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds stored in the  options: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Jul 04, 2017 8:57:19 PM net.sourceforge.ganttproject.GPLogger log
INFORMATION: RSS check finished
Jul 04, 2017 8:57:23 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories...
Jul 04, 2017 8:57:23 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/fonts
Jul 04, 2017 8:57:23 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:/windows/fonts
Jul 04, 2017 8:57:23 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory C:/windows/fonts is not readable
Jul 04, 2017 8:57:23 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/usr/share/fonts/truetype
Jul 04, 2017 8:57:23 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /usr/share/fonts/truetype is not readable
Jul 04, 2017 8:57:23 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/System/Library/Fonts
Jul 04, 2017 8:57:27 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/Applications/GanttProject.app/Contents/Java/plugins-2.8.5/org.ganttproject.impex.htmlpdf/resource/fonts
Jul 04, 2017 8:57:27 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories completed
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
`

And here is the one from this early morning.

`GanttProject 2.8.5 Pilsen (build 2179)
Settings file:
	location: /Users/sebastian/.ganttproject
	size:4096
	is readable: true
java.class.path: /Applications/GanttProject.app/Contents/Java/Classes:/Applications/GanttProject.app/Contents/Java/eclipsito.jar
java.home: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
java.ext.dirs: /Users/sebastian/Library/Java/Extensions:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
java.io.tmpdir: /var/folders/tw/g0f41qvx1b1_7h8k98s2nsz00000gn/T/
java.runtime.version: 1.8.0_131-b11
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.131-b11
os.arch: x86_64
os.name: Mac OS X
os.version: 10.12.5
sun.java.command: org.bardsoftware.eclipsito.Boot -app net.sourceforge.ganttproject.GanttProject -plugins-dir /Applications/GanttProject.app/Contents/Java/plugins-2.8.5 -log true
user.country: DE
user.dir: /Users/sebastian
user.home: /Users/sebastian
user.language: de
user.timezone: Europe/Paris

Jul 05, 2017 4:35:36 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Options file:/Users/sebastian/.ganttproject
Jul 05, 2017 4:35:37 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Waiting until main window closes
Jul 05, 2017 4:35:37 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
Jul 05, 2017 4:35:41 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds stored in the  options: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
8. finalizing...
Main frame created
Jul 05, 2017 4:35:41 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after setVisible: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Jul 05, 2017 4:35:41 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Starting RSS check...
Splash closed
Resizing window...
Jul 05, 2017 4:35:42 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after opening: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Jul 05, 2017 4:35:42 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds stored in the  options: java.awt.Rectangle[x=0,y=23,width=1440,height=873]
Jul 05, 2017 4:35:42 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: RSS check finished
Jul 05, 2017 4:35:46 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories...
Jul 05, 2017 4:35:46 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/fonts
Jul 05, 2017 4:35:46 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:/windows/fonts
Jul 05, 2017 4:35:46 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory C:/windows/fonts is not readable
Jul 05, 2017 4:35:46 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/usr/share/fonts/truetype
Jul 05, 2017 4:35:46 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /usr/share/fonts/truetype is not readable
Jul 05, 2017 4:35:46 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/System/Library/Fonts
Jul 05, 2017 4:35:50 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/Applications/GanttProject.app/Contents/Java/plugins-2.8.5/org.ganttproject.impex.htmlpdf/resource/fonts
Jul 05, 2017 4:35:50 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories completed
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
Jul 05, 2017 4:39:39 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: [GanttOptions] save(): finished!!
Jul 05, 2017 4:39:45 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: [GanttOptions] save(): finished!!
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
Jul 05, 2017 4:39:46 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Main window has closed
Jul 05, 2017 4:39:46 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Program terminated
Jul 05, 2017 4:39:46 AM org.bardsoftware.impl.eclipsito.BootImpl shutdown
INFORMATION: Eclipsito platform is shut down.
`

**Comment by ryanthara** [comment]
An additional crash occurs.

Here is the log.

[the top part is the same as above]

Jul 05, 2017 5:11:20 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories completed
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
Jul 05, 2017 5:13:00 AM net.sourceforge.ganttproject.GPLogger logToLogger
WARNUNG: I/O problems when accessing 
net.sourceforge.ganttproject.document.webdav.WebDavResource$WebDavException: I/O problems when accessing 
	at net.sourceforge.ganttproject.document.webdav.MiltonResourceImpl.getChildResources(MiltonResourceImpl.java:220)
	at net.sourceforge.ganttproject.document.webdav.GanttURLChooser$ReloadWorker.readChildren(GanttURLChooser.java:288)
	at net.sourceforge.ganttproject.document.webdav.GanttURLChooser$ReloadWorker.doInBackground(GanttURLChooser.java:273)
	at net.sourceforge.ganttproject.document.webdav.GanttURLChooser$ReloadWorker.doInBackground(GanttURLChooser.java:261)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http:///
	at org.apache.http.impl.client.AbstractHttpClient.determineTarget(AbstractHttpClient.java:817)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1043)
	at io.milton.httpclient.Host._doPropFind(Host.java:628)
	at io.milton.httpclient.Folder.children(Folder.java:131)
	at net.sourceforge.ganttproject.document.webdav.MiltonResourceImpl.getChildResources(MiltonResourceImpl.java:209)
	... 9 more
