### ISSUE TITLE
Gantt Project window doesn't start on linux (Fedora 26 - 32 bits)

### ISSUE THREAD

**Issue by topotech** [bardsoftware/ganttproject#1468]
Hi, when I try to start Gantt Project... nothing happens.

Binaries are stored in "/media/disco/ganttproject-2.8.5-r2179"

My java setup on ' /usr/lib/jvm':
```
java-1.8.0-openjdk-1.8.0.131-1.b12.fc25.i386
java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.i386
jre
jre-1.8.0
jre-1.8.0-openjdk
jre-1.8.0-openjdk-1.8.0.151-1.b12.fc26.i386
jre-openjdk
```

Here's my logfile on ~/.ganttproject.d
```
GanttProject 2.8.5 Pilsen (build 2179)
Settings file:
	location: /home/diego/.ganttproject
	size:0
	is readable: false
java.class.path: :/media/disco/ganttproject-2.8.5-r2179/eclipsito.jar:/media/disco/ganttproject-2.8.5-r2179
java.home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.i386/jre
java.ext.dirs: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.i386/jre/lib/ext:/usr/java/packages/lib/ext
java.io.tmpdir: /tmp
java.runtime.version: 1.8.0_151-b12
java.vendor: Oracle Corporation
java.vm.name: OpenJDK Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.151-b12
os.arch: i386
os.name: Linux
os.version: 4.13.10-200.fc26.i686+PAE
sun.java.command: org.bardsoftware.eclipsito.Boot ganttproject-eclipsito-config.xml -log true -log_file /home/diego/.ganttproject.d/.ganttproject-20171106220028.log
user.country: CL
user.dir: /media/disco/ganttproject-2.8.5-r2179
user.home: /home/diego
user.language: es
user.timezone: America/Santiago

nov 06, 2017 10:00:29 PM org.bardsoftware.impl.eclipsito.BootImpl$1 uncaughtException
ADVERTENCIA: [uncaughtException]java.awt.HeadlessException
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at net.sourceforge.ganttproject.GanttSplash.<init>(GanttSplash.java:32)
	at net.sourceforge.ganttproject.GanttProject$15.run(GanttProject.java:932)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

nov 06, 2017 10:00:30 PM net.sourceforge.ganttproject.GPLogger log
INFORMACIÓN: Waiting until main window closes
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at net.sourceforge.ganttproject.GanttProjectBase.<init>(GanttProjectBase.java:102)
	at net.sourceforge.ganttproject.GanttProject.<init>(GanttProject.java:154)
	at net.sourceforge.ganttproject.GanttProject$16.run(GanttProject.java:945)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
nov 06, 2017 10:00:30 PM org.bardsoftware.impl.eclipsito.BootImpl$1 uncaughtException
ADVERTENCIA: [uncaughtException]java.lang.NullPointerException
java.lang.NullPointerException
	at net.sourceforge.ganttproject.GanttProject$16.run(GanttProject.java:963)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

nov 06, 2017 10:00:39 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMACIÓN: Scanning font directories...
nov 06, 2017 10:00:39 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMACIÓN: scanning directory=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.i386/jre/lib/fonts
nov 06, 2017 10:00:39 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMACIÓN: directory /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.i386/jre/lib/fonts is not readable
nov 06, 2017 10:00:39 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMACIÓN: scanning directory=C:/windows/fonts
nov 06, 2017 10:00:39 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMACIÓN: directory C:/windows/fonts is not readable
nov 06, 2017 10:00:39 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMACIÓN: scanning directory=/usr/share/fonts/truetype
nov 06, 2017 10:00:39 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMACIÓN: directory /usr/share/fonts/truetype is not readable
nov 06, 2017 10:00:39 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMACIÓN: scanning directory=/System/Library/Fonts
nov 06, 2017 10:00:39 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMACIÓN: directory /System/Library/Fonts is not readable
nov 06, 2017 10:00:39 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMACIÓN: scanning directory=/media/disco/ganttproject-2.8.5-r2179/plugins-2.8.5/org.ganttproject.impex.htmlpdf/resource/fonts
nov 06, 2017 10:00:40 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMACIÓN: Scanning font directories completed
```

**Comment by dbarashev** [comment]
Do you have graphics environment on that machine?
