### ISSUE TITLE
Export failure. Failed subtask: Export project

### ISSUE THREAD

**Issue by Remirer** [bardsoftware/ganttproject#1520]
Export failure. Failed subtask: Export project
WARNING: Export failure. Failed subtask: Export project
java.lang.RuntimeException: Export failure. Failed subtask: Export project
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:167)
	at org.bardsoftware.impl.eclipsito.JobManagerImpl$GroupWorker.run(JobManagerImpl.java:163)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.convertStartTime(ProjectFileExporter.java:202)
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.exportTask(ProjectFileExporter.java:164)
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.exportTask(ProjectFileExporter.java:193)
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.exportTask(ProjectFileExporter.java:193)
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.exportTasks(ProjectFileExporter.java:142)
	at biz.ganttproject.impex.msproject2.ProjectFileExporter.run(ProjectFileExporter.java:68)
	at biz.ganttproject.impex.msproject2.ExporterToMsProjectFile$2.run(ExporterToMsProjectFile.java:118)
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:165)
	... 2 more

I have no custom columns in the project

**Comment by dbarashev** [comment]
Can you share the project file?

**Comment by Remirer** [comment]
No, but deleted one group of tasks and it works now, after restart.

**Comment by dbarashev** [comment]
That's a pity, we'd like to fix the root cause.

**Comment by Remirer** [comment]
hm

**Comment by Remirer** [comment]
Here it that bug-tusk only.
[buggy_task.zip](https://github.com/bardsoftware/ganttproject/files/1896262/buggy_task.zip)

**Comment by dbarashev** [comment]
Yup, thanks.

**Comment by Remirer** [comment]
Thank you!
