### ISSUE TITLE
Issues with Mac OSX integration on Java 9+

### ISSUE THREAD

**Issue by jamadam** [bardsoftware/ganttproject#1530]
Hi. 

I'd like to report a bug where double clicking .gen files opens new empty project. Dragging the files onto application does the same.

The only way I've found to open existing files is choosing files from "Project > Open" menu.

GanttProject 2.8.7 (and tried 2.8.6 too)
MacOS Sierra(10.12.6)

**Comment by dbarashev** [comment]
I can't reproduce it, sorry. Double click works fine on both Mac OSX systems which I use for testing (drag'n'drop is not expected to work because we didn't do anything for it).
You may need to "install" GanttProject by dragging it to Applications, however, if you say that double-click starts GP but just opens empty project then you probably have the required file associations.

Can you share the project file and the log after double-clicking? The log file `ganttproject.log` should sit in your home folder.

**Comment by jamadam** [comment]
Sorry for late.

As you said, double click opens GanttProject and opens empty project. 
I tried to deleted app and reinstall by dragging it into Applications. The result is the same.

I'll attach the project file and the log file.

[issue1530.zip](https://github.com/bardsoftware/ganttproject/files/1979339/issue1530.zip)

**Comment by dbarashev** [comment]
```
java.lang.NoSuchMethodError: com.apple.eawt.Application.addApplicationListener(Lcom/apple/eawt/ApplicationListener;)V
	at net.sourceforge.ganttproject.OSXAdapter.registerMacOSXApplication(OSXAdapter.java:107)
	at net.sourceforge.ganttproject.GanttProject$16.run(GanttProject.java:963)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Splash closed
```

**Comment by jamadam** [comment]
Thank you for looking into this.
I tried to downgrade java 8 and it worked!

**Comment by dbarashev** [comment]
I made a couple of fixes. May I ask you to test the new build on Java 10 on Mac? You can get the distro from here: https://www.dropbox.com/sh/0gwuayq6vg0kyss/AAApogLPlvpg0lY9JltS-3sZa?dl=0

**Comment by jamadam** [comment]
I tested the new one with java 10 on mac.

It seems to open new project first and then open the one I double clicked so save dialog is unexpectedly shown. I'll attach the log.

[ganttproject.log](https://github.com/bardsoftware/ganttproject/files/1986127/ganttproject.log)

**Comment by dbarashev** [comment]
Thanks for testing! Can you test one more build, `ganttproject-2.8.8-r2290.dmg` from the same Dropbox folder? It should remove the save dialog. Besides, ctrl+left button replaced with Cmd+left button in that build (see issue #1416)
