### ISSUE TITLE
Something went wrong after changing settings

### ISSUE THREAD

**Issue by darkside-e** [bardsoftware/ganttproject#1558]
hello, ganttproject won't work at all after I changed the dpi settings inside. I don't know exactly what is going on so I hope someone can help pls.
This is what i get when i enter it:
![screenshot00049](https://user-images.githubusercontent.com/34475779/40924588-5067ddde-6820-11e8-8f56-c8c27b380c71.png)
nothing is showing as you can see. I tried many keyboard shortcuts but I'm only getting a white screen and the java machine starts to act weird and slows my pc.
and this is an error i saw in the log file:
```
Uncaught error fetching image:
java.lang.ArrayIndexOutOfBoundsException: -1009
	at java.desktop/java.awt.image.ReplicateScaleFilter.setPixels(Unknown Source)
	at java.desktop/sun.awt.image.ImageDecoder.setPixels(Unknown Source)
	at java.desktop/sun.awt.image.PNGImageDecoder.sendPixels(Unknown Source)
	at java.desktop/sun.awt.image.PNGImageDecoder.produceImage(Unknown Source)
	at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(Unknown Source)
	at java.desktop/sun.awt.image.ImageFetcher.fetchloop(Unknown Source)
	at java.desktop/sun.awt.image.ImageFetcher.run(Unknown Source)
Uncaught error fetching image:
java.lang.ArrayIndexOutOfBoundsException: -1009
	at java.desktop/java.awt.image.ReplicateScaleFilter.setPixels(Unknown Source)
	at java.desktop/sun.awt.image.ImageDecoder.setPixels(Unknown Source)
	at java.desktop/sun.awt.image.PNGImageDecoder.sendPixels(Unknown Source)
	at java.desktop/sun.awt.image.PNGImageDecoder.produceImage(Unknown Source)
	at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(Unknown Source)
	at java.desktop/sun.awt.image.ImageFetcher.fetchloop(Unknown Source)
	at java.desktop/sun.awt.image.ImageFetcher.run(Unknown Source)
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
```

**Comment by dbarashev** [comment]
It appears that something is wrong with your logo image. The easiest thing which you can do is to remove your settings file. The name of the file is `.ganttproject` and it sits in your home folder. Note the dot in the file name, it may be hidden in some file system borwsers.

**Comment by darkside-e** [comment]
Thank you very much, it worked. And thanks again for the quick reply 👍
