### ISSUE TITLE
impossible to add task predecessor

### ISSUE THREAD

**Issue by PhilLAL** [bardsoftware/ganttproject#1631]
Hi, 
this issue is possbly linked to #1618 
I tried to add a predecessor to a task but Following 4 steps, I noticed that no predecessor has been added
I took some snapshots here: https://owncloud.lal.in2p3.fr/index.php/s/LxJhE1GmfeGVWHC
Do you confirm?

**Comment by dbarashev** [comment]
Please share a sample project. Thanks.

**Comment by PhilLAL** [comment]
Hi,
sorry for the delay, here is an example : https://owncloud.lal.in2p3.fr/index.php/s/I0J1rTs1aCcsmt4
Doing the steps today, I noticed following error : "Dependency=Gestion du projet : jalons->fin du CC effective is looping"
However, I do not find any useful information into the log.
Here is the log content:
```
/home/gauron/.ganttproject.d/.ganttproject-20190131115711.log

GanttProject 2.8.9 Pilsen (build 2335)
Settings file:
	location: /home/gauron/.ganttproject
	size:4945
	is readable: true
java.class.path: :/usr/share/ganttproject/eclipsito.jar:/usr/share/ganttproject
java.home: /usr/lib/jvm/java-8-openjdk-amd64/jre
java.ext.dirs: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext
java.io.tmpdir: /tmp
java.runtime.version: 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12
java.vendor: Oracle Corporation
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.191-b12
os.arch: amd64
os.name: Linux
os.version: 4.15.0-43-generic
sun.java.command: org.bardsoftware.eclipsito.Boot ganttproject-eclipsito-config.xml -log true -log_file /home/gauron/.ganttproject.d/.ganttproject-20190131115711.log /home/gauron/Documents/travail/projets/ThomX/CC/gantt/CC-ThomX.gan
user.country: FR
user.dir: /
user.home: /home/gauron
user.language: fr
user.timezone: Europe/Paris

janv. 31, 2019 12:57:11 PM net.sourceforge.ganttproject.GPLogger log
INFOS: Options file:/home/gauron/.ganttproject
janv. 31, 2019 12:57:12 PM net.sourceforge.ganttproject.GPLogger log
INFOS: Waiting until main window closes
janv. 31, 2019 12:57:12 PM net.sourceforge.ganttproject.GPLogger log
INFOS: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
janv. 31, 2019 12:57:13 PM net.sourceforge.ganttproject.GPLogger log
INFOS: Bounds stored in the  options: java.awt.Rectangle[x=2633,y=52,width=2446,height=1276]
8. finalizing...
Main frame created
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
janv. 31, 2019 12:57:14 PM net.sourceforge.ganttproject.GPLogger log
INFOS: Bounds after setVisible: java.awt.Rectangle[x=2633,y=52,width=2446,height=1276]
janv. 31, 2019 12:57:14 PM net.sourceforge.ganttproject.GPLogger log
INFOS: Starting RSS check...
Splash closed
Resizing window...
janv. 31, 2019 12:57:14 PM net.sourceforge.ganttproject.GPLogger log
INFOS: Bounds after opening: java.awt.Rectangle[x=3840,y=80,width=1280,height=1276]
janv. 31, 2019 12:57:14 PM net.sourceforge.ganttproject.GPLogger log
INFOS: Bounds stored in the  options: java.awt.Rectangle[x=2633,y=52,width=2446,height=1276]
janv. 31, 2019 12:57:15 PM net.sourceforge.ganttproject.GPLogger log
INFOS: RSS check finished
janv. 31, 2019 12:57:21 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFOS: Scanning font directories...
janv. 31, 2019 12:57:21 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: scanning directory=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/fonts
janv. 31, 2019 12:57:21 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: directory /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/fonts is not readable
janv. 31, 2019 12:57:21 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: scanning directory=C:/windows/fonts
janv. 31, 2019 12:57:21 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: directory C:/windows/fonts is not readable
janv. 31, 2019 12:57:21 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: scanning directory=/usr/share/fonts/truetype
janv. 31, 2019 12:57:22 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: scanning directory=/System/Library/Fonts
janv. 31, 2019 12:57:22 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: directory /System/Library/Fonts is not readable
janv. 31, 2019 12:57:22 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: scanning directory=/usr/share/ganttproject/plugins-2.8.9/org.ganttproject.impex.htmlpdf/resource/fonts
janv. 31, 2019 12:57:22 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFOS: Scanning font directories completed
janv. 31, 2019 12:59:57 PM net.sourceforge.ganttproject.GPLogger logToLogger
AVERTISSEMENT: Dependency=Gestion du projet : jalons->fin du CC effective is looping
net.sourceforge.ganttproject.task.dependency.TaskDependencyException: Dependency=Gestion du projet : jalons->fin du CC effective is looping
	at net.sourceforge.ganttproject.task.dependency.TaskDependencyCollectionImpl.addDependency(TaskDependencyCollectionImpl.java:257)
	at net.sourceforge.ganttproject.task.dependency.TaskDependencyCollectionImpl$MutatorImpl.commit(TaskDependencyCollectionImpl.java:164)
	at net.sourceforge.ganttproject.gui.taskproperties.DependencyTableModel.commit(DependencyTableModel.java:93)
	at net.sourceforge.ganttproject.gui.taskproperties.TaskDependenciesPanel.commit(TaskDependenciesPanel.java:102)
	at net.sourceforge.ganttproject.gui.GanttTaskPropertiesBean.applySettings(GanttTaskPropertiesBean.java:435)
	at net.sourceforge.ganttproject.gui.GanttDialogProperties$1$1.run(GanttDialogProperties.java:50)
	at net.sourceforge.ganttproject.undo.UndoableEditImpl.<init>(UndoableEditImpl.java:48)
	at net.sourceforge.ganttproject.undo.UndoManagerImpl.undoableEdit(UndoManagerImpl.java:74)
	at net.sourceforge.ganttproject.gui.GanttDialogProperties$1.actionPerformed(GanttDialogProperties.java:47)
	at net.sourceforge.ganttproject.DialogBuilder$1$1.run(DialogBuilder.java:208)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at net.sourceforge.ganttproject.DialogBuilder$DialogImpl.show(DialogBuilder.java:148)
	at net.sourceforge.ganttproject.gui.GanttDialogProperties.show(GanttDialogProperties.java:73)
	at net.sourceforge.ganttproject.action.task.TaskPropertiesAction.run(TaskPropertiesAction.java:66)
	at net.sourceforge.ganttproject.action.task.TaskActionBase$2.run(TaskActionBase.java:86)
	at net.sourceforge.ganttproject.undo.UndoableEditImpl.<init>(UndoableEditImpl.java:48)
	at net.sourceforge.ganttproject.undo.UndoManagerImpl.undoableEdit(UndoManagerImpl.java:74)
	at net.sourceforge.ganttproject.action.task.TaskActionBase.actionPerformed(TaskActionBase.java:82)
	at net.sourceforge.ganttproject.GPTreeTableBase.editCellAt(GPTreeTableBase.java:150)
	at javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(BasicTableUI.java:1108)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(BasicTableUI.java:1038)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at org.jdesktop.swingx.JXTreeTable.processMouseEvent(JXTreeTable.java:449)
	at net.sourceforge.ganttproject.GPTreeTableBase.processMouseEvent(GPTreeTableBase.java:187)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

janv. 31, 2019 12:59:57 PM net.sourceforge.ganttproject.GPLogger logToLogger
AVERTISSEMENT: Dependency=préparation démarrage Ligne X->fin du CC effective is looping
net.sourceforge.ganttproject.task.dependency.TaskDependencyException: Dependency=préparation démarrage Ligne X->fin du CC effective is looping
	at net.sourceforge.ganttproject.task.dependency.TaskDependencyCollectionImpl.addDependency(TaskDependencyCollectionImpl.java:257)
	at net.sourceforge.ganttproject.task.dependency.TaskDependencyCollectionImpl$MutatorImpl.commit(TaskDependencyCollectionImpl.java:164)
	at net.sourceforge.ganttproject.gui.taskproperties.DependencyTableModel.commit(DependencyTableModel.java:93)
	at net.sourceforge.ganttproject.gui.taskproperties.TaskDependenciesPanel.commit(TaskDependenciesPanel.java:102)
	at net.sourceforge.ganttproject.gui.GanttTaskPropertiesBean.applySettings(GanttTaskPropertiesBean.java:435)
	at net.sourceforge.ganttproject.gui.GanttDialogProperties$1$1.run(GanttDialogProperties.java:50)
	at net.sourceforge.ganttproject.undo.UndoableEditImpl.<init>(UndoableEditImpl.java:48)
	at net.sourceforge.ganttproject.undo.UndoManagerImpl.undoableEdit(UndoManagerImpl.java:74)
	at net.sourceforge.ganttproject.gui.GanttDialogProperties$1.actionPerformed(GanttDialogProperties.java:47)
	at net.sourceforge.ganttproject.DialogBuilder$1$1.run(DialogBuilder.java:208)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at net.sourceforge.ganttproject.DialogBuilder$DialogImpl.show(DialogBuilder.java:148)
	at net.sourceforge.ganttproject.gui.GanttDialogProperties.show(GanttDialogProperties.java:73)
	at net.sourceforge.ganttproject.action.task.TaskPropertiesAction.run(TaskPropertiesAction.java:66)
	at net.sourceforge.ganttproject.action.task.TaskActionBase$2.run(TaskActionBase.java:86)
	at net.sourceforge.ganttproject.undo.UndoableEditImpl.<init>(UndoableEditImpl.java:48)
	at net.sourceforge.ganttproject.undo.UndoManagerImpl.undoableEdit(UndoManagerImpl.java:74)
	at net.sourceforge.ganttproject.action.task.TaskActionBase.actionPerformed(TaskActionBase.java:82)
	at net.sourceforge.ganttproject.GPTreeTableBase.editCellAt(GPTreeTableBase.java:150)
	at javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(BasicTableUI.java:1108)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(BasicTableUI.java:1038)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at org.jdesktop.swingx.JXTreeTable.processMouseEvent(JXTreeTable.java:449)
	at net.sourceforge.ganttproject.GPTreeTableBase.processMouseEvent(GPTreeTableBase.java:187)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by dbarashev** [comment]
The message is true, you _really_ have a dependency loop.
1. `fin du CC effective` (=A)  is a subtask of `Gestion du project: jalons` (=B)  => end date(A) <= end date(B)
1. There is finish-start dependency between B and `configuration moteur shutter (1)` (=C) => end date(B) < end date(C)
1. C is a subtask of `préparation démarrage Ligne X` (=D) => end date(C) <= end date(D)
1. You request D to be a predecessor of A => end date (D) < end date (A)

Concluding, A <= B < C <= D < A -- that's the loop.

**Comment by PhilLAL** [comment]
Thank you.
Is there a simple way to check the dependencies when you have several tasks involved? I have to say that I miss this one. :)
