### ISSUE TITLE
Import iCalendar Error

### ISSUE THREAD

**Issue by tshepoth** [bardsoftware/ganttproject#1670]
Tried to import iCalendar file through the import wizard but got the following error, using GanttProject 2.8.10 :

/Users/tshepothlaku/ganttproject.log

GanttProject 2.8.10 Pilsen (build 2363)
Settings file:
	location: /Users/tshepothlaku/.ganttproject
	size:5663
	is readable: true
java.class.path: /Applications/GanttProject.app/Contents/Java/Classes:/Applications/GanttProject.app/Contents/Java/eclipsito.jar
java.home: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
java.ext.dirs: /Users/tshepothlaku/Library/Java/Extensions:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
java.io.tmpdir: /var/folders/53/j9xtxj5s29bg39mg4w89hdpw0000gn/T/
java.runtime.version: 1.8.0_211-b12
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.211-b12
os.arch: x86_64
os.name: Mac OS X
os.version: 10.14.5
sun.java.command: org.bardsoftware.eclipsito.Boot -app net.sourceforge.ganttproject.GanttProject -plugins-dir /Applications/GanttProject.app/Contents/Java/plugins-2.8.10 -log true
user.country: ZA
user.dir: /Users/tshepothlaku
user.home: /Users/tshepothlaku
user.language: en
user.timezone: Africa/Johannesburg

Jul 04, 2019 9:40:32 PM net.sourceforge.ganttproject.GPLogger log
INFO: Options file:/Users/tshepothlaku/.ganttproject
Jul 04, 2019 9:40:33 PM net.sourceforge.ganttproject.GPLogger log
INFO: Waiting until main window closes
Jul 04, 2019 9:40:33 PM net.sourceforge.ganttproject.GPLogger log
INFO: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
Jul 04, 2019 9:40:37 PM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds stored in the  options: java.awt.Rectangle[x=38,y=23,width=1402,height=796]
8. finalizing...
Main frame created
Jul 04, 2019 9:40:37 PM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds after setVisible: java.awt.Rectangle[x=38,y=23,width=1402,height=796]
Splash closed
Resizing window...
Jul 04, 2019 9:40:37 PM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds after opening: java.awt.Rectangle[x=38,y=23,width=1402,height=796]
Jul 04, 2019 9:40:37 PM net.sourceforge.ganttproject.GPLogger log
INFO: Bounds stored in the  options: java.awt.Rectangle[x=38,y=23,width=1402,height=796]
Jul 04, 2019 9:40:42 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFO: Scanning font directories...
Jul 04, 2019 9:40:42 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/fonts
Jul 04, 2019 9:40:42 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=C:/windows/fonts
Jul 04, 2019 9:40:42 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: directory C:/windows/fonts is not readable
Jul 04, 2019 9:40:42 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/usr/share/fonts/truetype
Jul 04, 2019 9:40:42 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: directory /usr/share/fonts/truetype is not readable
Jul 04, 2019 9:40:42 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/System/Library/Fonts
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
Jul 04, 2019 9:40:46 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFO: scanning directory=/Applications/GanttProject.app/Contents/Java/plugins-2.8.10/org.ganttproject.impex.htmlpdf/resource/fonts
Jul 04, 2019 9:40:46 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFO: Scanning font directories completed
Jul 04, 2019 9:44:38 PM net.fortuna.ical4j.util.Configurator <clinit>
INFO: ical4j.properties not found.
Jul 04, 2019 9:44:38 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: null
java.lang.NullPointerException
	at biz.ganttproject.impex.ical.IcsFileImporter.readEvents(IcsFileImporter.java:175)
	at biz.ganttproject.impex.ical.IcsFileImporter.setFile(IcsFileImporter.java:101)
	at net.sourceforge.ganttproject.importer.FileChooserPage.setFile(FileChooserPage.java:74)
	at net.sourceforge.ganttproject.wizard.AbstractFileChooserPage.onSelectedFileChange(AbstractFileChooserPage.java:288)
	at net.sourceforge.ganttproject.wizard.AbstractFileChooserPage.loadPreferences(AbstractFileChooserPage.java:202)
	at net.sourceforge.ganttproject.wizard.AbstractFileChooserPage.setActive(AbstractFileChooserPage.java:228)
	at net.sourceforge.ganttproject.wizard.AbstractWizard.nextPage(AbstractWizard.java:111)
	at net.sourceforge.ganttproject.wizard.AbstractWizard.access$000(AbstractWizard.java:42)
	at net.sourceforge.ganttproject.wizard.AbstractWizard$1.actionPerformed(AbstractWizard.java:77)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at net.sourceforge.ganttproject.DialogBuilder$DialogImpl.show(DialogBuilder.java:148)
	at net.sourceforge.ganttproject.wizard.AbstractWizard.show(AbstractWizard.java:151)
	at net.sourceforge.ganttproject.action.project.ProjectImportAction.actionPerformed(ProjectImportAction.java:50)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:357)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:345)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:763)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dbarashev** [comment]
Can you please share the file?

**Comment by tshepoth** [comment]
Below is the link of file, however, I can't navigate to the next screen to even select the file 

https://www.thunderbird.net/media/caldata/SouthAfricaHolidays.ics

**Comment by tshepoth** [comment]
Not sure what to do

**Comment by dbarashev** [comment]
Thanks for the link.

It is a bug, I committed a bugfix to the repository. If you have some programming experience, you can compile the build with bugfix from the sources, otherwise, wait until the next release.
If you're curios what caused the problem and can you fix it by updating the source file: it was missing SUMMARY field in some of the events.

**Comment by tshepoth** [comment]
Thanks a lot
