### ISSUE TITLE
.gan file not find by ganttproject

### ISSUE THREAD

**Issue by logicielem** [bardsoftware/ganttproject#1724]
Hello,
I have a .gan file from a project partner. 
When I click on the file, I can see the opening popup of ganttproject but the application don't open.
When I open ganttproject and then I try to open the .gan file by browsing my directories, ganttproject don't show the .gan file in the list ; it can't find it.
Is there a log file for ganttproject where I could analyse the cause of this issue ?

I work with 2.5.4 version from Mageia Linux 7.

**Comment by logicielem** [comment]
I've found the log in my home directory/.ganttproject.d/ and there is the java error reported : 
1. loading look'n'feels
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. changing look'n'feel ...
8. finalizing...
Main frame created
java.lang.ArrayIndexOutOfBoundsException: -1
	at net.sourceforge.ganttproject.ResourceTreeTableModel.getColumnName(ResourceTreeTableModel.java:326)
	at org.jdesktop.swing.JXTreeTable$TreeTableModelAdapter.getColumnName(JXTreeTable.java:1235)
	at javax.swing.JTable.addColumn(Unknown Source)
	at net.sourceforge.ganttproject.GPTreeTableBase$TableHeaderUiFacadeImpl.insertColumnIntoUi(GPTreeTableBase.java:253)
	at net.sourceforge.ganttproject.GPTreeTableBase$TableHeaderUiFacadeImpl.importData(GPTreeTableBase.java:214)
	at net.sourceforge.ganttproject.parser.TaskDisplayColumnsTagHandler.parsingFinished(TaskDisplayColumnsTagHandler.java:77)
	at net.sourceforge.ganttproject.io.GanttXMLOpen$GanttXMLParser.endDocument(GanttXMLOpen.java:263)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at net.sourceforge.ganttproject.io.GanttXMLOpen.load(GanttXMLOpen.java:110)
	at net.sourceforge.ganttproject.document.ProxyDocument$ParsingState.enter(ProxyDocument.java:338)
	at net.sourceforge.ganttproject.document.ProxyDocument.read(ProxyDocument.java:172)
	at net.sourceforge.ganttproject.GanttProject.open(GanttProject.java:662)
	at net.sourceforge.ganttproject.gui.ProjectUIFacadeImpl.openProject(ProjectUIFacadeImpl.java:268)
	at net.sourceforge.ganttproject.GanttProject$9.run(GanttProject.java:685)
	at net.sourceforge.ganttproject.undo.UndoableEditImpl.<init>(UndoableEditImpl.java:47)
	at net.sourceforge.ganttproject.undo.UndoManagerImpl.undoableEdit(UndoManagerImpl.java:64)
	at net.sourceforge.ganttproject.GanttProject.openStartupDocument(GanttProject.java:681)
	at net.sourceforge.ganttproject.GanttProject.main(GanttProject.java:888)
	at net.sourceforge.ganttproject.application.MainApplication.run(MainApplication.java:37)
	at org.bardsoftware.impl.eclipsito.ApplicationLauncher.launchApplication(ApplicationLauncher.java:29)
	at org.bardsoftware.impl.eclipsito.BootImpl$2.run(BootImpl.java:53)
Splash closed
mars 04, 2020 11:11:30 AM net.sourceforge.ganttproject.GPLogger log
INFOS: Program terminated

**Comment by dbarashev** [comment]
> I work with 2.5.4 version from Mageia Linux 7.

Wait... 2.5.4? It was released eight years ago. Why don't you upgrade?

**Comment by logicielem** [comment]
I simply installed the version present in Mageia 7.
OK I'll try with the last version.

**Comment by logicielem** [comment]
OK. Solved after installing 2.8.10 Pilsen release and renaming my .ganttproject file and .ganttproject.d directory.
Thank you dbarashev !
