### ISSUE TITLE
ControlsFX Exception: Not detecting Java 11 (OpenJDK)

### ISSUE THREAD

**Issue by joeriexelmans** [bardsoftware/ganttproject#1732]
GanttProject version: 748a9cea57282fc372f36c61dd270b98bee34650 (latest commit on 'master')
Java: OpenJDK 11.0.6 
OS: Ubuntu 19.10

I'm running GanttProject from IntelliJ using Gradle plugin.

When opening "My Projects...", I get an uncaught exception:

`java.lang.RuntimeException: ControlsFX Error: ControlsFX 11.0.1 requires at least Java Version 9
	at impl.org.controlsfx.version.VersionChecker.doVersionCheck(VersionChecker.java:96)
	at org.controlsfx.control.ControlsFXControl.<init>(ControlsFXControl.java:35)
	at org.controlsfx.control.PropertySheet.<init>(PropertySheet.java:227)
	at org.controlsfx.control.PropertySheet.<init>(PropertySheet.java:218)
	at biz.ganttproject.storage.webdav.WebdavServerSetupPane.doCreateUi(WebdavServerSetupPane.java:71)
	at biz.ganttproject.storage.webdav.WebdavServerSetupPane.createUi(WebdavServerSetupPane.java:61)
	at biz.ganttproject.storage.webdav.WebdavStorage.createSettingsUi(WebdavStorage.kt:106)
	at biz.ganttproject.storage.StoragePane.reloadStorages(Storage.kt:187)
	at biz.ganttproject.storage.StoragePane.reloadStorages$default(Storage.kt:143)
	at biz.ganttproject.storage.StoragePane.buildStoragePane(Storage.kt:130)
	at biz.ganttproject.storage.StorageDialogBuilder.buildStoragePane(StorageDialogBuilder.kt:165)
	at biz.ganttproject.storage.StorageDialogBuilder.showOpenStorageUi(StorageDialogBuilder.kt:146)
	at biz.ganttproject.storage.StorageDialogBuilder.access$showOpenStorageUi(StorageDialogBuilder.kt:48)
	at biz.ganttproject.storage.StorageDialogBuilder$build$$inlined$apply$lambda$2.handle(StorageDialogBuilder.kt:108)
	at biz.ganttproject.storage.StorageDialogBuilder$build$$inlined$apply$lambda$2.handle(StorageDialogBuilder.kt:48)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8865)
	at javafx.controls/javafx.scene.control.Button.fire(Button.java:200)
	at biz.ganttproject.storage.StorageDialogBuilder.build(StorageDialogBuilder.kt:138)
	at biz.ganttproject.storage.StorageDialogAction$actionPerformed$1$1.invoke(StorageDialogAction.kt:44)
	at biz.ganttproject.storage.StorageDialogAction$actionPerformed$1$1.invoke(StorageDialogAction.kt:34)
	at biz.ganttproject.app.DialogKt$dialog$1.run(Dialog.kt:99)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

Thanks in advance

**Comment by joeriexelmans** [comment]
When running "./gradlew runApp" from terminal, everything is fine.

Only running "runApp" from IntelliJ gives the error above. So it's perhaps more an IntelliJ issue.

**Comment by joeriexelmans** [comment]
Not sure how I fixed it, but one of the following things must've done it:
I re-imported the build.gradle file into IntelliJ.
In IntelliJ, menu File -> Project Structure... -> SDKs: Changed JVM 11's path from IntelliJ's (/snap/intellij-idea-community/...) to the one installed in /usr/lib/jvm/.... 
Things are working now so I'm closing this issue.
