### ISSUE TITLE
Invalid range / IllegalArgumentException when deleting activies

### ISSUE THREAD

**Issue by alinuxexpert** [bardsoftware/ganttproject#1755]
I deleted a range of activities and then another one. Then I got the following error notification of an invalid range:

```
C:\Users\xxx\ganttproject.log

GanttProject 2.8.11 Pilsen (build 2396)
Settings file:
	location: C:\Users\xxx\.ganttproject
	size:4561
	is readable: true
java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject-2.8
java.home: C:\Program Files\Java\jre1.8.0_261
java.ext.dirs: C:\Program Files\Java\jre1.8.0_261\lib\ext;C:\Windows\Sun\Java\lib\ext
java.io.tmpdir: C:\Users\xxx\AppData\Local\Temp\
java.runtime.version: 1.8.0_261-b12
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: Oracle Corporation
java.vm.version: 25.261-b12
os.arch: amd64
os.name: Windows 10
os.version: 10.0
sun.java.command: org.bardsoftware.eclipsito.Boot -plugins-dir plugins -app net.sourceforge.ganttproject.GanttProject -log true C:\Users\xxx\SECRET\Zeitplan.gan
user.country: DE
user.dir: C:\Program Files (x86)\GanttProject-2.8
user.home: C:\Users\xxx
user.language: de
user.timezone: Europe/Berlin

Jul 24, 2020 10:11:02 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Options file:C:\Users\xxx\.ganttproject
Jul 24, 2020 10:11:03 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Waiting until main window closes
Jul 24, 2020 10:11:03 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
Jul 24, 2020 10:11:05 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds stored in the  options: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
8. finalizing...
Main frame created
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
Jul 24, 2020 10:11:05 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after setVisible: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
Splash closed
Resizing window...
Jul 24, 2020 10:11:06 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after opening: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
Jul 24, 2020 10:11:06 AM net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds stored in the  options: java.awt.Rectangle[x=-8,y=-8,width=1936,height=1056]
Jul 24, 2020 10:11:12 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories...
Jul 24, 2020 10:11:12 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:\Program Files\Java\jre1.8.0_261/lib/fonts
Jul 24, 2020 10:11:12 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:/windows/fonts
Jul 24, 2020 10:11:20 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/usr/share/fonts/truetype
Jul 24, 2020 10:11:20 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /usr/share/fonts/truetype is not readable
Jul 24, 2020 10:11:20 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/System/Library/Fonts
Jul 24, 2020 10:11:20 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /System/Library/Fonts is not readable
Jul 24, 2020 10:11:20 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/C:/Program Files (x86)/GanttProject-2.8/plugins/2.8.11/org.ganttproject.impex.htmlpdf/resource/fonts
Jul 24, 2020 10:11:20 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories completed
Jul 24, 2020 10:17:41 AM net.sourceforge.ganttproject.GPLogger logToLogger
WARNUNG: Invalid range: [Mon Dec 14 00:00:00 UTC 2020?Sat Dec 12 00:00:00 UTC 2020]
java.lang.IllegalArgumentException: Invalid range: [Mon Dec 14 00:00:00 UTC 2020?Sat Dec 12 00:00:00 UTC 2020]
	at com.google.common.collect.Range.<init>(Range.java:366)
	at com.google.common.collect.Range.create(Range.java:156)
	at com.google.common.collect.Range.closed(Range.java:180)
	at net.sourceforge.ganttproject.task.algorithm.SchedulerImpl.schedule(SchedulerImpl.java:152)
	at net.sourceforge.ganttproject.task.algorithm.SchedulerImpl.doRun(SchedulerImpl.java:109)
	at net.sourceforge.ganttproject.task.algorithm.SchedulerImpl.run(SchedulerImpl.java:97)
	at net.sourceforge.ganttproject.task.algorithm.SchedulerImpl$1.onChange(SchedulerImpl.java:66)
	at net.sourceforge.ganttproject.task.algorithm.DependencyGraph.fireGraphChanged(DependencyGraph.java:911)
	at net.sourceforge.ganttproject.task.algorithm.DependencyGraph.removeTask(DependencyGraph.java:681)
	at net.sourceforge.ganttproject.task.TaskManagerImpl.fireTaskRemoved(TaskManagerImpl.java:768)
	at net.sourceforge.ganttproject.task.TaskManagerImpl.deleteTask(TaskManagerImpl.java:329)
	at net.sourceforge.ganttproject.action.task.TaskDeleteAction.run(TaskDeleteAction.java:92)
	at net.sourceforge.ganttproject.action.task.TaskActionBase$2.run(TaskActionBase.java:86)
	at net.sourceforge.ganttproject.undo.UndoableEditImpl.<init>(UndoableEditImpl.java:48)
	at net.sourceforge.ganttproject.undo.UndoManagerImpl.undoableEdit(UndoManagerImpl.java:74)
	at net.sourceforge.ganttproject.action.task.TaskActionBase.actionPerformed(TaskActionBase.java:82)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by dbarashev** [comment]
Can you please share the file where this issue is reproducible and the scenario of reproducing?

**Comment by alinuxexpert** [comment]
I cannot reproduce this bug, thus, I'm closing the issue.
