### ISSUE TITLE
distZip from master creates not working deploy

### ISSUE THREAD

**Issue by uschmidt-velian** [bardsoftware/ganttproject#1797]
I build a distZip (using Ubuntu 18.04 and the BellSoft Full OpenJDK 11).
However the release is nor startable on Windows 10 or my linux system

If I start the app using "runApp" everything works fine.
If I run the ganttproject.bat on my Windows system I get this Stack Trace
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.split(String)" because "storeSpec" is null
 at com.bardsoftware.eclipsito.runtime.ModuleRuntime.getVersionLayerStoreDirs(ModuleRuntime.java:90)
 at com.bardsoftware.eclipsito.runtime.ModuleRuntime.build(ModuleRuntime.java:50)
 at com.bardsoftware.eclipsito.runtime.RunLoop.start(RunLoop.java:32)
 at com.bardsoftware.eclipsito.Launch.main(Launch.java:37)
```

If I run the bash script (this also happens if a run "distbin")

```
/home/uli/ganttproject-2.99-r2913/runtime/bin/java does not exist
```

Why does it tries to run a java runtime in the current directory?
I have a JDK installed at my system and my java executable is located in /usr/bin/java

**Comment by dbarashev** [comment]
On Linux you can run `ganttproject -j` (-j allows for specifying the path to Java Runtime and by default it takes the value from JAVA_HOME or uses `java` command from the path if JAVA_HOME is not set.

Thanks for reporting `ganttproject.bat` issue.

> Why does it tries to run a java runtime in the current directory?

Because most people do not have JDK installed. GP 3.0 for Windows and macOS (and maybe for Linux too) will come with its own Java Runtime which will reside in `runtime` directory.
