### ISSUE TITLE
Calender timeline must have 53 weeks

### ISSUE THREAD

**Issue by markus-kessler** [bardsoftware/ganttproject#1801]
As you can seee a screenshot from my GanttProject timeline with 52 weeks. 
But this year has 53 weeks as you can see at the Outlook Calender Screenshot.

I did not find a setting in GanttProject like in Outlook.

<img width="260" alt="gantt-timeline" src="https://user-images.githubusercontent.com/75613136/101337977-a75e3000-387c-11eb-9653-4245b0e4f2e3.PNG">
<img width="135" alt="outlook-calender" src="https://user-images.githubusercontent.com/75613136/101338057-c066e100-387c-11eb-9108-f6361d92f992.PNG">

**Comment by dbarashev** [comment]
It works fine in my GanttProject with German translation.
Please share the log file to be able to detect what's wrong in this case. Help > View log

**Comment by markus-kessler** [comment]
**Logfile created 07-012-2020**

C:\Users\kessler\ganttproject.log

GanttProject 2.8.11 Pilsen (build 2396)
Settings file:
	location: C:\Users\kessler\.ganttproject
	size:5507
	is readable: true
java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject-2.8
java.home: C:\Program Files\Amazon Corretto\jdk11.0.8_10
java.ext.dirs: null
java.io.tmpdir: C:\Users\kessler\AppData\Local\Temp\
java.runtime.version: 11.0.8+10-LTS
java.vendor: Amazon.com Inc.
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.vendor: Amazon.com Inc.
java.vm.version: 11.0.8+10-LTS
os.arch: amd64
os.name: Windows 10
os.version: 10.0
sun.java.command: org.bardsoftware.eclipsito.Boot -plugins-dir plugins -app net.sourceforge.ganttproject.GanttProject -log true
user.country: DE
user.dir: C:\Program Files (x86)\GanttProject-2.8
user.home: C:\Users\kessler
user.language: de
user.timezone: Europe/Berlin

Dez. 07, 2020 10:28:19 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Options file:C:\Users\kessler\.ganttproject
Dez. 07, 2020 10:28:20 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Waiting until main window closes
Dez. 07, 2020 10:28:20 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
Dez. 07, 2020 10:28:22 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds stored in the  options: java.awt.Rectangle[x=-5,y=1,width=2548,height=1398]
8. finalizing...
Main frame created
Dez. 07, 2020 10:28:22 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after setVisible: java.awt.Rectangle[x=-5,y=1,width=2548,height=1398]
Dez. 07, 2020 10:28:22 VORM. net.sourceforge.ganttproject.GPLogger logToLogger
WARNUNG: The APP_ABOUT action is not supported on the current platform!
java.lang.UnsupportedOperationException: The APP_ABOUT action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
	at java.desktop/java.awt.Desktop.setAboutHandler(Desktop.java:696)
	at biz.ganttproject.desktop.DesktopAdapter.install(DesktopAdapter.java:22)
	at net.sourceforge.ganttproject.DesktopIntegration.setup(DesktopIntegration.java:29)
	at net.sourceforge.ganttproject.GanttProject$15.run(GanttProject.java:1031)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Splash closed
Resizing window...
Dez. 07, 2020 10:28:22 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after opening: java.awt.Rectangle[x=-5,y=1,width=2548,height=1398]
Dez. 07, 2020 10:28:22 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds stored in the  options: java.awt.Rectangle[x=-5,y=1,width=2548,height=1398]
Dez. 07, 2020 10:28:29 VORM. org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories...
Dez. 07, 2020 10:28:29 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:\Program Files\Amazon Corretto\jdk11.0.8_10/lib/fonts
Dez. 07, 2020 10:28:29 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory C:\Program Files\Amazon Corretto\jdk11.0.8_10/lib/fonts is not readable
Dez. 07, 2020 10:28:29 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:/windows/fonts
Dez. 07, 2020 10:28:31 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/usr/share/fonts/truetype
Dez. 07, 2020 10:28:31 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /usr/share/fonts/truetype is not readable
Dez. 07, 2020 10:28:31 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/System/Library/Fonts
Dez. 07, 2020 10:28:31 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /System/Library/Fonts is not readable
Dez. 07, 2020 10:28:31 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/C:/Program Files (x86)/GanttProject-2.8/plugins/2.8.11/org.ganttproject.impex.htmlpdf/resource/fonts
Dez. 07, 2020 10:28:31 VORM. org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories completed

**Comment by markus-kessler** [comment]
C:\Users\kessler\ganttproject.log

GanttProject 2.8.11 Pilsen (build 2396)
Settings file:
              location: C:\Users\kessler\.ganttproject
              size:5507
              is readable: true
java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject-2.8
java.home: C:\Program Files\Amazon Corretto\jdk11.0.8_10
java.ext.dirs: null
java.io.tmpdir: C:\Users\kessler\AppData\Local\Temp\
java.runtime.version: 11.0.8+10-LTS
java.vendor: Amazon.com Inc.
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.vendor: Amazon.com Inc.
java.vm.version: 11.0.8+10-LTS
os.arch: amd64
os.name: Windows 10
os.version: 10.0
sun.java.command: org.bardsoftware.eclipsito.Boot -plugins-dir plugins -app net.sourceforge.ganttproject.GanttProject -log true
user.country: DE
user.dir: C:\Program Files (x86)\GanttProject-2.8
user.home: C:\Users\kessler
user.language: de
user.timezone: Europe/Berlin

Dez. 07, 2020 10:28:19 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Options file:C:\Users\kessler\.ganttproject
Dez. 07, 2020 10:28:20 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Waiting until main window closes
Dez. 07, 2020 10:28:20 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
Dez. 07, 2020 10:28:22 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds stored in the  options: java.awt.Rectangle[x=-5,y=1,width=2548,height=1398]
8. finalizing...
Main frame created
Dez. 07, 2020 10:28:22 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after setVisible: java.awt.Rectangle[x=-5,y=1,width=2548,height=1398]
Dez. 07, 2020 10:28:22 VORM. net.sourceforge.ganttproject.GPLogger logToLogger
WARNUNG: The APP_ABOUT action is not supported on the current platform!
java.lang.UnsupportedOperationException: The APP_ABOUT action is not supported on the current platform!
              at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
              at java.desktop/java.awt.Desktop.setAboutHandler(Desktop.java:696)
              at biz.ganttproject.desktop.DesktopAdapter.install(DesktopAdapter.java:22)
              at net.sourceforge.ganttproject.DesktopIntegration.setup(DesktopIntegration.java:29)
              at net.sourceforge.ganttproject.GanttProject$15.run(GanttProject.java:1031)
              at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
              at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
              at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
              at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
              at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
              at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
              at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
              at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Splash closed
Resizing window...
Dez. 07, 2020 10:28:22 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds after opening: java.awt.Rectangle[x=-5,y=1,width=2548,height=1398]
Dez. 07, 2020 10:28:22 VORM. net.sourceforge.ganttproject.GPLogger log
INFORMATION: Bounds stored in the  options: java.awt.Rectangle[x=-5,y=1,width=2548,height=1398]
Dez. 07, 2020 10:28:29 VORM. org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories...
Dez. 07, 2020 10:28:29 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:\Program Files\Amazon Corretto\jdk11.0.8_10/lib/fonts
Dez. 07, 2020 10:28:29 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory C:\Program Files\Amazon Corretto\jdk11.0.8_10/lib/fonts is not readable
Dez. 07, 2020 10:28:29 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=C:/windows/fonts
Dez. 07, 2020 10:28:31 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/usr/share/fonts/truetype
Dez. 07, 2020 10:28:31 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /usr/share/fonts/truetype is not readable
Dez. 07, 2020 10:28:31 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/System/Library/Fonts
Dez. 07, 2020 10:28:31 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: directory /System/Library/Fonts is not readable
Dez. 07, 2020 10:28:31 VORM. org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFORMATION: scanning directory=/C:/Program Files (x86)/GanttProject-2.8/plugins/2.8.11/org.ganttproject.impex.htmlpdf/resource/fonts
Dez. 07, 2020 10:28:31 VORM. org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFORMATION: Scanning font directories completed

Mit freundlichen Grüßen | Best regards

Markus Kessler
Geschäftsführer
Produktentwicklung, Vertrieb

[cid:image001.png@01D6CC8C.7AFE4420]

concept electronic GmbH | Westring 55 | 33818 Leopoldshöhe | Germany

Fon    +49 (0) 5202 92 88 3 18
Mobil +49 (0) 1523 17 117 33
Fon    +49 (0) 5202 92 88 3 0  Innendienst
Fax     +49 (0) 5202 92 88 3 20

Von: Dmitry Barashev <notifications@github.com>
Gesendet: Montag, 7. Dezember 2020 11:28
An: bardsoftware/ganttproject <ganttproject@noreply.github.com>
Cc: Markus Kessler <kessler@concept-electronic.de>; Author <author@noreply.github.com>
Betreff: Re: [bardsoftware/ganttproject] Calender timeline must have 53 weeks (#1801)


It works fine in my GanttProject with German translation.
Please share the log file to be able to detect what's wrong in this case. Help > View log

**Comment by dbarashev** [comment]
Thanks! 
Can you please check if it is reproducible in the beta of GP 3.0? You can download it from https://www.ganttproject.biz/download#download30

**Comment by markus-kessler** [comment]
Works 😊
Thanks a lot

**Comment by 5pekkie** [comment]
I downloaded the version dbareshev recommended (and also run the update) but I still don't have week 53 displayed.

here is my log file
C:\Users\admin\ganttproject.log

GanttProject 3.0.2917
Settings file:
	location: C:\Users\admin\.ganttproject
	size:5487
	is readable: true
java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject-3.0
java.home: C:\Program Files (x86)\GanttProject-3.0\runtime
java.ext.dirs: null
java.io.tmpdir: C:\Users\admin\AppData\Local\Temp\
java.runtime.version: 11.0.9.1+1-LTS
java.vendor: BellSoft
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.vendor: BellSoft
java.vm.version: 11.0.9.1+1-LTS
os.arch: amd64
os.name: Windows 10
os.version: 10.0
sun.java.command: com.bardsoftware.eclipsito.Launch --verbosity 1 --version-dirs plugins;~/.ganttproject.d/updates --app net.sourceforge.ganttproject.GanttProject
user.country: US
user.dir: C:\Program Files (x86)\GanttProject-3.0
user.home: C:\Users\admin
user.language: en
user.timezone: Europe/Berlin

Jan 19, 2021 9:18:42 AM net.sourceforge.ganttproject.GPLogger log
INFO: Deleting old auto-save files
Jan 19, 2021 9:18:43 AM biz.ganttproject.LoggerImpl debug
FINE: Creating main frame...
Jan 19, 2021 9:18:43 AM biz.ganttproject.LoggerImpl debug
FINE: 1. loading look'n'feels
Jan 19, 2021 9:18:43 AM biz.ganttproject.LoggerImpl debug
FINE: 2. loading options
Jan 19, 2021 9:18:43 AM biz.ganttproject.LoggerImpl debug
FINE: 3. creating menus...
Jan 19, 2021 9:18:43 AM biz.ganttproject.LoggerImpl debug
FINE: 4. creating views...
Jan 19, 2021 9:18:44 AM biz.ganttproject.LoggerImpl debug
FINE: 5. calculating size and packing...
Jan 19, 2021 9:18:44 AM biz.ganttproject.LoggerImpl debug
FINE: 6. changing language ...
Jan 19, 2021 9:18:44 AM biz.ganttproject.LoggerImpl debug
FINE: 7. first attempt to restore bounds
Jan 19, 2021 9:18:44 AM biz.ganttproject.LoggerImpl debug
FINE: 8. finalizing...

**Comment by markus-kessler** [comment]
Hi 5pekkie, 

year 2021 has got 52 weeks only. That is correct.

Regards
Markus

**Comment by 5pekkie** [comment]
![image](https://user-images.githubusercontent.com/77667322/105016397-e1594f00-5a42-11eb-8bc0-f1029e76c019.png)
Yeah but because 2020 has got 53 weeks, week 1 from 2021 starts wrong

**Comment by markus-kessler** [comment]
ok, thats the same problem I have had. After installing version 2.99.2913 it works. I have no more idea. sorry.

**Comment by dbarashev** [comment]
> user.language: en

This interface language implies English (US) and uses the US calendar conventions. In US week # 1 starts in December.
If you want English interface language and European conventions about the first week, change the language to English (UK).

**Comment by 5pekkie** [comment]
Can't get it right 
I've tried to set the language (and region) to UK but it keeps saying user.language: en, user.country does change to GB.
Even reinstalling GanttProject does not fix it.
Also tried to set it to dutch, but even that don't help.

user.country: NL
user.dir: C:\Program Files (x86)\GanttProject-3.0
user.home: C:\Users\admin
user.language: nl
user.timezone: Europe/Berlin

**Comment by tomgru** [comment]
same problem here. I am using 3.0.3004 on macOS.

Current week is WK11, but Gantt says it is WK12. How can I fix this?

![Screenshot 2021-03-18 at 12 25 06](https://user-images.githubusercontent.com/7261259/111618825-1e448680-87e5-11eb-8b61-6360001071f5.png)

many thanks,
tom
