### ISSUE TITLE
error on openSUSE Leap 15.3

### ISSUE THREAD

**Issue by Yarrax** [bardsoftware/ganttproject#2004]
I install ganntprojects from OBS: https://build.opensuse.org/package/show/Office/ganttproject
I used jre-11-openjdk and bellsoft-java8-full.
Always a got error on open file form:
янв. 31, 2022 8:42:04 PM net.sourceforge.ganttproject.GPLogger log
INFO: Deleting old auto-save files
янв. 31, 2022 8:42:09 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: class impl.org.controlsfx.skin.NotificationPaneSkin (in unnamed module @0x79a24271) cannot access class com.sun.javafx.scene.traversal.ParentTraversalEngine (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene.traversal to unnamed module @0x79a24271
java.lang.IllegalAccessError: class impl.org.controlsfx.skin.NotificationPaneSkin (in unnamed module @0x79a24271) cannot access class com.sun.javafx.scene.traversal.ParentTraversalEngine (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene.traversal to unnamed module @0x79a24271
	at impl.org.controlsfx.skin.NotificationPaneSkin.<init>(NotificationPaneSkin.java:117)
	at org.controlsfx.control.NotificationPane.createDefaultSkin(NotificationPane.java:227)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9558)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9551)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9551)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9551)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:569)
	at javafx.graphics/javafx.scene.Scene.access$3400(Scene.java:172)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2480)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:414)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:413)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:440)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:520)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:500)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:493)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:321)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:829)

java -version
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-suse-3.68.1-x8664)
OpenJDK 64-Bit Server VM (build 11.0.13+8-suse-3.68.1-x8664, mixed mode)

java -version
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)

**Comment by dbarashev** [comment]
1. You need __Java 11__ from __BellSoft__. 
2. By the way, the logs look as if you actually used Java 16 (which started throwing IllegalAccessError). 
3. I don't know anything about  OpenSUSE builds. Please contact the maintainers of that package if you want to use it, or use the official ZIP distro and the appropriate Java Runtime
