### ISSUE TITLE
Can't create a new task

### ISSUE THREAD

**Issue by gwijnja** [bardsoftware/ganttproject#2067]
I thought let's give GanttProject a try. Literally within a minute it crashes, not the best first impression.

Here's a video showing the issue: https://www.youtube.com/watch?v=oJ9_tW4Aot0

Steps to reproduce:

1) Open GanttProject
2) Right-click in the tasks-list on the left and select "New task". A new task appears, with the cursor flashing next to it's name. But I don't change it, I simply click somewhere else so the task keeps the default name "taak_0" (yes, taak, not task. Which is also weird, I have a Dutch Windows, GanttProject is set to English, but the task default name is still in Dutch "taak". but anyway, moving on...)
4) I right-click on that task and select Delete Task. The task is gone.
5) I repeat step 2, so I right-click again and select "New task"

A pop-up appears in the lower right corner: "Something went wrong".

"View log" reveals this:

> C:\Users\gerbe\ganttproject.log
> 
> GanttProject 3.2.3230
> Settings file:
> 	location: C:\Users\gerbe\.ganttproject
> 	size:4667
> 	is readable: true
> java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject-3.2
> java.home: C:\Program Files (x86)\GanttProject-3.2\runtime
> java.ext.dirs: null
> java.io.tmpdir: C:\Users\gerbe\AppData\Local\Temp\
> java.runtime.version: 11.0.13+8-LTS
> java.vendor: BellSoft
> java.vm.name: OpenJDK 64-Bit Server VM
> java.vm.vendor: BellSoft
> java.vm.version: 11.0.13+8-LTS
> os.arch: amd64
> os.name: Windows 10
> os.version: 10.0
> sun.java.command: com.bardsoftware.eclipsito.Launch --verbosity 1 --version-dirs plugins;~/.ganttproject.d/updates --app net.sourceforge.ganttproject.GanttProject
> user.country: NL
> user.dir: C:\Program Files (x86)\GanttProject-3.2
> user.home: C:\Users\gerbe
> user.language: nl
> user.timezone: Europe/Berlin
> 
> mrt. 25, 2022 1:35:57 P.M. biz.ganttproject.LoggerImpl debug
> FINE: Creating main frame...
> mrt. 25, 2022 1:35:57 P.M. biz.ganttproject.LoggerImpl debug
> FINE: 1. loading look'n'feels
> mrt. 25, 2022 1:35:58 P.M. biz.ganttproject.LoggerImpl debug
> FINE: 2. loading options
> Mar 25, 2022 1:35:58 PM biz.ganttproject.LoggerImpl debug
> FINE: 3. creating menus...
> Mar 25, 2022 1:35:58 PM biz.ganttproject.LoggerImpl debug
> FINE: 4. creating views...
> Mar 25, 2022 1:35:59 PM biz.ganttproject.LoggerImpl debug
> FINE: 5. calculating size and packing...
> Mar 25, 2022 1:35:59 PM biz.ganttproject.LoggerImpl debug
> FINE: 6. changing language ...
> Mar 25, 2022 1:35:59 PM biz.ganttproject.LoggerImpl debug
> FINE: 7. first attempt to restore bounds
> Mar 25, 2022 1:35:59 PM biz.ganttproject.LoggerImpl debug
> FINE: 8. finalizing...
> Mar 25, 2022 1:35:59 PM net.sourceforge.ganttproject.GPLogger log
> INFO: Deleting old auto-save files
> Mar 25, 2022 1:38:01 PM net.sourceforge.ganttproject.GPLogger logToLogger
> WARNING: null
> java.lang.NullPointerException
> 	at net.sourceforge.ganttproject.task.TaskImpl.move(TaskImpl.java:511)
> 	at net.sourceforge.ganttproject.task.FacadeImpl.move(TaskTreeFacade.kt:78)
> 	at net.sourceforge.ganttproject.task.TaskManagerImpl$10.build(TaskManagerImpl.java:366)
> 	at net.sourceforge.ganttproject.action.task.TaskNewAction.lambda$actionPerformed$0(TaskNewAction.java:78)
> 	at net.sourceforge.ganttproject.undo.UndoableEditImpl.<init>(UndoableEditImpl.java:46)
> 	at net.sourceforge.ganttproject.undo.UndoManagerImpl.undoableEdit(UndoManagerImpl.java:72)
> 	at net.sourceforge.ganttproject.action.task.TaskNewAction.actionPerformed(TaskNewAction.java:67)
> 	at biz.ganttproject.app.MenuKt.asMenuItem$lambda-13$lambda-11$lambda-10(Menu.kt:222)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> 	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
> 	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
>

**Comment by dbarashev** [comment]
Thanks for reporting!
