### ISSUE TITLE
Task list not showing (Java Zulu 17 & 18)

### ISSUE THREAD

**Issue by luistoledo** [bardsoftware/ganttproject#2151]
Tasks list not displaying properly

![image](https://user-images.githubusercontent.com/46700/172919074-199aae03-7d57-4227-9ed0-3d61d267f645.png)

Message
```
**Something went wrong**

com/sun/javafx/scene/control/behavior/TextBinding com.sun.javafx.scene.control.behavior.TextBinding
```

Log
```
/home/luis/.ganttproject.d/logs/.ganttproject-20220608180114.log

GanttProject 3.2.3240
Settings file:
	location: /home/luis/.ganttproject
	size:6218
	is readable: true
java.class.path: :/opt/ganttproject/eclipsito.jar:/opt/ganttproject
java.home: /home/luis/.sdkman/candidates/java/17.0.3.fx-zulu
java.ext.dirs: null
java.io.tmpdir: /tmp
java.runtime.version: 17.0.3+7-LTS
java.vendor: Azul Systems, Inc.
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.vendor: Azul Systems, Inc.
java.vm.version: 17.0.3+7-LTS
os.arch: amd64
os.name: Linux
os.version: 5.15.41-1-MANJARO
sun.java.command: com.bardsoftware.eclipsito.Launch --app net.sourceforge.ganttproject.GanttProject --version-dirs /opt/ganttproject/plugins:~/.ganttproject.d/updates -log true -log_file /home/luis/.ganttproject.d/logs/.ganttproject-20220608180114.log
user.country: US
user.dir: /home/luis
user.home: /home/luis
user.language: en
user.timezone: America/Mexico_City

Jun 08, 2022 11:01:16 PM biz.ganttproject.LoggerImpl debug
FINE: Creating main frame...
Jun 08, 2022 11:01:16 PM biz.ganttproject.LoggerImpl debug
FINE: 1. loading look'n'feels
Jun 08, 2022 11:01:17 PM biz.ganttproject.LoggerImpl debug
FINE: 2. loading options
Jun 08, 2022 11:01:17 PM biz.ganttproject.LoggerImpl debug
FINE: 3. creating menus...
Jun 08, 2022 11:01:17 PM biz.ganttproject.LoggerImpl debug
FINE: 4. creating views...
Jun 08, 2022 11:01:18 PM biz.ganttproject.LoggerImpl debug
FINE: 5. calculating size and packing...
Jun 08, 2022 11:01:18 PM biz.ganttproject.LoggerImpl debug
FINE: 6. changing language ...
Jun 08, 2022 11:01:18 PM biz.ganttproject.LoggerImpl debug
FINE: 7. first attempt to restore bounds
Jun 08, 2022 11:01:18 PM biz.ganttproject.LoggerImpl debug
FINE: 8. finalizing...
Jun 08, 2022 11:01:18 PM net.sourceforge.ganttproject.GPLogger log
INFO: Deleting old auto-save files
Jun 08, 2022 11:01:23 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: com/sun/javafx/scene/control/behavior/TextBinding
java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/behavior/TextBinding
	at biz.ganttproject.lib.fx.treetable.LabeledSkinBase.updateDisplayedText(LabeledSkinBase.java:960)
	at biz.ganttproject.lib.fx.treetable.LabeledSkinBase.layoutLabelInArea(LabeledSkinBase.java:537)
	at biz.ganttproject.lib.fx.treetable.LabeledSkinBase.layoutLabelInArea(LabeledSkinBase.java:460)
	at biz.ganttproject.lib.fx.treetable.TableCellSkinBase.layoutChildren(TableCellSkinBase.java:145)
	at javafx.controls/javafx.scene.control.Control.layoutChildren(Control.java:601)
	at javafx.controls/javafx.scene.control.Cell.layoutChildren(Cell.java:636)
	at javafx.controls/javafx.scene.control.TreeTableCell.layoutChildren(TreeTableCell.java:714)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1207)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:579)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2499)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:405)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:404)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:434)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:575)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.scene.control.behavior.TextBinding
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at com.bardsoftware.eclipsito.runtime.BundleClassLoader.findClass(BundleClassLoader.java:128)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 27 more
```

system info
```
System:
  Host: ---- Kernel: 5.15.41-1-MANJARO
    arch: x86_64 bits: 64 Desktop: Xfce v: 4.16.0
    Distro: Manjaro Linux
```

java version
```
$ java --version
openjdk 17.0.3 2022-04-19 LTS
OpenJDK Runtime Environment Zulu17.34+19-CA (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.34+19-CA (build 17.0.3+7-LTS, mixed mode, sharing)
```

**Comment by dbarashev** [comment]
We recommend using  DEB distro on Linux, which includes the required JavaFX libraries. If you're using ZIP distro, Java 11 FX is recommended.

**Comment by Mishasama** [comment]
Same here with [BellSoft Liberica JRE 18 Full](https://bell-sw.com/pages/downloads/#/java-18-current) running on Windows.

Is GP only support Java 11? But not the newer versions?

**Comment by dbarashev** [comment]
We support long-term support (LTS) releases, and we're conservative. Java 11 is a LTS. Java 17 is LTS as well, but it appeared less than 1 year ago. 
Package for Windows comes with its own bundled JRE which was tested. If you use your own JRE, be prepared for possible issues.

**Comment by Mishasama** [comment]
> We support long-term support (LTS) releases, and we're conservative. Java 11 is a LTS. Java 17 is LTS as well, but it appeared less than 1 year ago. Package for Windows comes with its own bundled JRE which was tested. If you use your own JRE, be prepared for possible issues.

Thanks for the fast response. I can feel the GP running at [JRE 17.0.4+8-LTS](https://download.bell-sw.com/java/17.0.4+8/bellsoft-jdk17.0.4+8-windows-amd64.msi) is much faster and responsive than 11.
It seems no problem for now.
