### ISSUE TITLE
Error when adding a new task in a project with "hide completed tasks" filter switched on

### ISSUE THREAD

**Issue by zacabbeymarketing** [bardsoftware/ganttproject#2198]
hi,

I'm getting this error every time i try to create a new task.
log below.
this is a hard error and i cannot do anything further.

C:\Users\zac\ganttproject.log

GanttProject 3.2.3245
Settings file:
	location: C:\Users\zac\.ganttproject
	size:6410
	is readable: true
java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject-3.2
java.home: C:\Program Files (x86)\GanttProject-3.2\runtime
java.ext.dirs: null
java.io.tmpdir: C:\Users\zac\AppData\Local\Temp\
java.runtime.version: 11.0.13+8-LTS
java.vendor: BellSoft
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.vendor: BellSoft
java.vm.version: 11.0.13+8-LTS
os.arch: amd64
os.name: Windows 10
os.version: 10.0
sun.java.command: com.bardsoftware.eclipsito.Launch --verbosity 1 --version-dirs plugins;~/.ganttproject.d/updates --app net.sourceforge.ganttproject.GanttProject C:\Users\zac\Desktop\Work 290622.gan
user.country: GB
user.dir: C:\Program Files (x86)\GanttProject-3.2
user.home: C:\Users\zac
user.language: en
user.timezone: Europe/London

Jul 18, 2022 1:08:48 PM biz.ganttproject.LoggerImpl debug
FINE: Creating main frame...
Jul 18, 2022 1:08:48 PM biz.ganttproject.LoggerImpl debug
FINE: 1. loading look'n'feels
Jul 18, 2022 1:08:49 PM biz.ganttproject.LoggerImpl debug
FINE: 2. loading options
Jul 18, 2022 1:08:49 PM biz.ganttproject.LoggerImpl debug
FINE: 3. creating menus...
Jul 18, 2022 1:08:50 PM biz.ganttproject.LoggerImpl debug
FINE: 4. creating views...
Jul 18, 2022 1:08:50 PM biz.ganttproject.LoggerImpl debug
FINE: 5. calculating size and packing...
Jul 18, 2022 1:08:50 PM biz.ganttproject.LoggerImpl debug
FINE: 6. changing language ...
Jul 18, 2022 1:08:50 PM biz.ganttproject.LoggerImpl debug
FINE: 7. first attempt to restore bounds
Jul 18, 2022 1:08:50 PM biz.ganttproject.LoggerImpl debug
FINE: 8. finalizing...
Jul 18, 2022 1:08:51 PM net.sourceforge.ganttproject.GPLogger log
INFO: Deleting old auto-save files
Jul 18, 2022 1:09:18 PM net.sourceforge.ganttproject.GPLogger log
INFO: [GanttOptions] save(): finished!!
Jul 18, 2022 1:09:48 PM net.sourceforge.ganttproject.GPLogger log
INFO: [GanttOptions] save(): finished!!
Jul 18, 2022 1:10:20 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: Index: 20, Size: 17
java.lang.IndexOutOfBoundsException: Index: 20, Size: 17
	at java.base/java.util.ArrayList.rangeCheckForAdd(Unknown Source)
	at java.base/java.util.ArrayList.add(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ObservableListWrapper.doAdd(Unknown Source)
	at javafx.base/javafx.collections.ModifiableObservableListBase.add(Unknown Source)
	at biz.ganttproject.ganttview.TaskTable.addChildTreeItem(TaskTable.kt:687)
	at biz.ganttproject.ganttview.TaskTable.access$addChildTreeItem(TaskTable.kt:84)
	at biz.ganttproject.ganttview.TaskTable$initTaskEventHandlers$1$taskAdded$2.invokeSuspend(TaskTable.kt:335)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by dbarashev** [comment]
Please share your project file.

**Comment by zacabbeymarketing** [comment]
Regards,
Zac Amor
General Manager

Unit 4 Oak  Industrial Park
Great Dunmow
Essex
CM6 1XN
01371 873333
www.abbeymarketing.com<http://www.abbeymarketing.com/>
Direct Mail & Plastic Card Specialists

***@***.***

**Comment by dbarashev** [comment]
I suppose that you meant to attach a file, but GitHub issue tracker (which you replied to) doesn't support attachment in email replies, sorry. Please attach it in the web interface or send it by email to contact@ganttproject.biz
