### ISSUE TITLE
PDF-Export via CLI does not work

### ISSUE THREAD

**Issue by niklasbautz** [bardsoftware/ganttproject#2227]
Hey,
first of all I want to thank you for this software.

I am currently working on a project where it is required to automate the export of the diagram. 

My first attempt was to do this via the cli.

The command I use is:
```
 ./GanttProject -export pdf ~/__REPOS__/bachelorarbeit/etc/Bachelorarbeit.gan
```
Which generates the following output.
```
Aug. 30, 2022 10:52:46 NACHM. com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$getVersionLayerStoreDirs$5
FEIN: Path `plugins` is not absolute. We'll try resolving it relative to user.dir=/Applications/GanttProject.app/Contents/app
Aug. 30, 2022 10:52:46 NACHM. com.bardsoftware.eclipsito.runtime.ModuleRuntime build
FEIN: We will run with the following plugins:
Aug. 30, 2022 10:52:46 NACHM. com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin org.ganttproject.chart.pert-3.2.3240 at /Applications/GanttProject.app/Contents/app/plugins/base/org.ganttproject.chart.pert/plugin.xml
Aug. 30, 2022 10:52:46 NACHM. com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin biz.ganttproject.impex.msproject2-3.2.3240 at /Applications/GanttProject.app/Contents/app/plugins/base/biz.ganttproject.impex.msproject2/plugin.xml
Aug. 30, 2022 10:52:46 NACHM. com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin biz.ganttproject.app.localization-3.2.3240 at /Applications/GanttProject.app/Contents/app/plugins/base/biz.ganttproject.app.localization/plugin.xml
Aug. 30, 2022 10:52:46 NACHM. com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin biz.ganttproject.impex.ical-3.2.3240 at /Applications/GanttProject.app/Contents/app/plugins/base/biz.ganttproject.impex.ical/plugin.xml
Aug. 30, 2022 10:52:46 NACHM. com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin org.ganttproject.impex.htmlpdf-3.2.3240 at /Applications/GanttProject.app/Contents/app/plugins/base/org.ganttproject.impex.htmlpdf/plugin.xml
Aug. 30, 2022 10:52:46 NACHM. com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin net.sourceforge.ganttproject-3.2.3240 at /Applications/GanttProject.app/Contents/app/plugins/base/ganttproject/plugin.xml
Aug. 30, 2022 10:52:46 NACHM. com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin biz.ganttproject.app.libs-3.2.3240 at /Applications/GanttProject.app/Contents/app/plugins/base/biz.ganttproject.app.libs/plugin.xml
Aug. 30, 2022 10:52:46 NACHM. com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin biz.ganttproject.core-3.2.3240 at /Applications/GanttProject.app/Contents/app/plugins/base/biz.ganttproject.core/plugin.xml
Aug. 30, 2022 10:52:46 NACHM. com.bardsoftware.eclipsito.runtime.Runner run
FEIN: Command line args: [-export, pdf, /Users/niklasb/__REPOS__/bachelorarbeit/etc/Bachelorarbeit.gan]
Aug. 30, 2022 10:52:46 NACHM. com.bardsoftware.eclipsito.runtime.Runner run
FEIN: Launching application=net.sourceforge.ganttproject.GanttProject
```

The PDF file which is generated in the folder of the .gan file is broken and cannot be read by any pdf editor.

I would appreciate any help with this.

Thank you in advance.

**Comment by dbarashev** [comment]
Thanks for reporting. Seems to be a bug, will be fixed in the next update.

For the record, a stack trace when exporting to PDF using CLI on Linux (the same on macOS)

```
java.lang.NullPointerException
        at org.ganttproject.impex.htmlpdf.itext.ThemeImpl.getFontName(ThemeImpl.java:207)
        at org.ganttproject.impex.htmlpdf.itext.ThemeImpl.getSansRegularBold(ThemeImpl.java:219)
        at org.ganttproject.impex.htmlpdf.itext.ThemeImpl.createColontitleTable(ThemeImpl.java:560)
        at org.ganttproject.impex.htmlpdf.itext.ThemeImpl.writeTitlePage(ThemeImpl.java:302)
        at org.ganttproject.impex.htmlpdf.itext.ThemeImpl.writeProject(ThemeImpl.java:268)
        at org.ganttproject.impex.htmlpdf.itext.ThemeImpl.run(ThemeImpl.java:258)
        at org.ganttproject.impex.htmlpdf.itext.ITextEngine$3.run(ITextEngine.java:217)
        at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:180)
        at org.bardsoftware.impl.eclipsito.JobManagerImpl$GroupWorker.run(JobManagerImpl.java:163)
        at java.base/java.lang.Thread.run(Thread.java:829)
[ConsoleUIFacade] ERROR: Export failure. Failed subtask: Generating PDF
java.lang.RuntimeException: Export failure. Failed subtask: Generating PDF
        at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:182)
        at org.bardsoftware.impl.eclipsito.JobManagerImpl$GroupWorker.run(JobManagerImpl.java:163)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: ExceptionConverter: java.io.IOException: The document has no pages.
Caused by: java.io.IOException: The document has no pages.
        at com.itextpdf.text.pdf.PdfPages.writePageTree(PdfPages.java:112)
        at com.itextpdf.text.pdf.PdfWriter.close(PdfWriter.java:1256)
        at com.itextpdf.text.pdf.PdfDocument.close(PdfDocument.java:901)
        at com.itextpdf.text.Document.close(Document.java:415)
        at org.ganttproject.impex.htmlpdf.itext.ThemeImpl.run(ThemeImpl.java:263)
        at org.ganttproject.impex.htmlpdf.itext.ITextEngine$3.run(ITextEngine.java:217)
        at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:180)
        at org.bardsoftware.impl.eclipsito.JobManagerImpl$GroupWorker.run(JobManagerImpl.java:163)
        at java.base/java.lang.Thread.run(Thread.java:829)
Aug 30, 2022 10:42:45 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: Export failure. Failed subtask: Generating PDF
java.lang.RuntimeException: Export failure. Failed subtask: Generating PDF
        at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:182)
        at org.bardsoftware.impl.eclipsito.JobManagerImpl$GroupWorker.run(JobManagerImpl.java:163)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: ExceptionConverter: java.io.IOException: The document has no pages.
Caused by: java.io.IOException: The document has no pages.
        at com.itextpdf.text.pdf.PdfPages.writePageTree(PdfPages.java:112)
        at com.itextpdf.text.pdf.PdfWriter.close(PdfWriter.java:1256)
        at com.itextpdf.text.pdf.PdfDocument.close(PdfDocument.java:901)
        at com.itextpdf.text.Document.close(Document.java:415)
        at org.ganttproject.impex.htmlpdf.itext.ThemeImpl.run(ThemeImpl.java:263)
        at org.ganttproject.impex.htmlpdf.itext.ITextEngine$3.run(ITextEngine.java:217)
        at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:180)
        at org.bardsoftware.impl.eclipsito.JobManagerImpl$GroupWorker.run(JobManagerImpl.java:163)
        at java.base/java.lang.Thread.run(Thread.java:829)



!!!!!!!!!!! canceling family=Export job family
```
