### ISSUE TITLE
Jave heap out of memory error in windows while moving tasks using arrow keys

### ISSUE THREAD

**Issue by wcadams55** [bardsoftware/ganttproject#2256]
Error occurs when scrolling through the task list using arrow keys and using the Alt+Arrows to rearrange tasks. Sometimes Shift selecting to move several around at a time.

C:\Users\wcada\ganttproject.log

GanttProject 3.2.3246
Settings file:
	location: C:\Users\wcada\.ganttproject
	size:5400
	is readable: true
java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject-3.2
java.home: C:\Program Files (x86)\GanttProject-3.2\runtime
java.ext.dirs: null
java.io.tmpdir: C:\Users\wcada\AppData\Local\Temp\
java.runtime.version: 11.0.13+8-LTS
java.vendor: BellSoft
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.vendor: BellSoft
java.vm.version: 11.0.13+8-LTS
os.arch: amd64
os.name: Windows 10
os.version: 10.0
sun.java.command: com.bardsoftware.eclipsito.Launch --verbosity 1 --version-dirs plugins;~/.ganttproject.d/updates --app net.sourceforge.ganttproject.GanttProject
user.country: US
user.dir: C:\Program Files (x86)\GanttProject-3.2
user.home: C:\Users\wcada
user.language: en
user.timezone: America/New_York

Oct 16, 2022 1:05:40 AM biz.ganttproject.LoggerImpl debug
FINE: Creating main frame...
Oct 16, 2022 1:05:40 AM biz.ganttproject.LoggerImpl debug
FINE: 1. loading look'n'feels
Oct 16, 2022 1:05:40 AM biz.ganttproject.LoggerImpl debug
FINE: 2. loading options
Oct 16, 2022 1:05:40 AM biz.ganttproject.LoggerImpl debug
FINE: 3. creating menus...
Oct 16, 2022 1:05:40 AM biz.ganttproject.LoggerImpl debug
FINE: 4. creating views...
Oct 16, 2022 1:05:40 AM biz.ganttproject.LoggerImpl debug
FINE: 5. calculating size and packing...
Oct 16, 2022 1:05:41 AM biz.ganttproject.LoggerImpl debug
FINE: 6. changing language ...
Oct 16, 2022 1:05:41 AM biz.ganttproject.LoggerImpl debug
FINE: 7. first attempt to restore bounds
Oct 16, 2022 1:05:41 AM biz.ganttproject.LoggerImpl debug
FINE: 8. finalizing...
Oct 16, 2022 1:05:41 AM net.sourceforge.ganttproject.GPLogger log
INFO: Deleting old auto-save files
Oct 16, 2022 1:06:10 AM net.sourceforge.ganttproject.GPLogger log
INFO: [GanttOptions] save(): finished!!
Oct 16, 2022 1:06:10 AM net.sourceforge.ganttproject.GPLogger log
INFO: [GanttOptions] save(): finished!!
Oct 16, 2022 1:06:10 AM biz.ganttproject.LoggerImpl error
SEVERE: WebSocket closed. Code=1000, reason=Reset Websocket
Oct 16, 2022 1:06:10 AM biz.ganttproject.LoggerImpl error
SEVERE: WebSocket has been closed
Oct 16, 2022 1:07:14 AM net.sourceforge.ganttproject.GPLogger log
INFO: [GanttOptions] save(): finished!!
Oct 16, 2022 1:07:28 AM net.sourceforge.ganttproject.GPLogger log
INFO: [GanttOptions] save(): finished!!
Oct 16, 2022 1:07:32 AM net.sourceforge.ganttproject.GPLogger log
INFO: [GanttOptions] save(): finished!!
Oct 16, 2022 1:07:34 AM net.sourceforge.ganttproject.GPLogger log
INFO: [GanttOptions] save(): finished!!
java.lang.OutOfMemoryError: Java heap space
Oct 16, 2022 1:47:44 AM com.bardsoftware.eclipsito.runtime.RunLoop$1 uncaughtException
WARNING: [uncaughtException]java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space

Oct 16, 2022 1:47:44 AM com.bardsoftware.eclipsito.runtime.RunLoop$1 uncaughtException
WARNING: [uncaughtException]java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space

Oct 16, 2022 1:47:44 AM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: Java heap space
java.lang.OutOfMemoryError: Java heap space
	at javafx.graphics/com.sun.javafx.css.StyleManager.processStylesheets(Unknown Source)
	at javafx.graphics/com.sun.javafx.css.StyleManager.gatherParentStylesheets(Unknown Source)
	at javafx.graphics/com.sun.javafx.css.StyleManager.findMatchingStyles(Unknown Source)
	at javafx.graphics/javafx.scene.CssStyleHelper.createStyleHelper(Unknown Source)
	at javafx.graphics/javafx.scene.Node.reapplyCss(Unknown Source)
	at javafx.graphics/javafx.scene.Node.reapplyCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Unknown Source)
	at javafx.graphics/javafx.scene.Node.setScenes(Unknown Source)
	at javafx.graphics/javafx.scene.Parent$2.onChanged(Unknown Source)
	at javafx.base/com.sun.javafx.collections.TrackableObservableList.lambda$new$0(Unknown Source)
	at javafx.base/com.sun.javafx.collections.TrackableObservableList$$Lambda$127/0x00000001001bb040.onChanged(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at javafx.base/javafx.collections.ModifiableObservableListBase.add(Unknown Source)
	at java.base/java.util.AbstractList.add(Unknown Source)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.add(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.getAvailableCell(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.addLeadingCells(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.scrollPixels(Unknown Source)
	at biz.ganttproject.lib.fx.GPTreeTableViewSkin.scrollBy(TreeTable.kt:243)
	at biz.ganttproject.lib.fx.GPTreeTableView.scrollBy(TreeTable.kt:98)
	at biz.ganttproject.ganttview.TaskTable.initChartConnector$lambda-22$lambda-21(TaskTable.kt:261)
	at biz.ganttproject.ganttview.TaskTable$$Lambda$1688/0x0000000100b5cc40.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl$$Lambda$119/0x00000001001bd840.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl$$Lambda$118/0x00000001001be440.run(Unknown Source)

Oct 16, 2022 1:47:44 AM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: Java heap space
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/sun.font.Font2D.updateLastStrikeRef(Unknown Source)
	at java.desktop/sun.font.Font2D.getStrike(Unknown Source)
	at java.desktop/sun.font.Font2D.getStrike(Unknown Source)
	at java.desktop/sun.font.Font2D.getFontMetrics(Unknown Source)
	at java.desktop/java.awt.Font.defaultLineMetrics(Unknown Source)
	at java.desktop/java.awt.Font.getLineMetrics(Unknown Source)
	at java.desktop/sun.font.StandardGlyphVector.getLogicalBounds(Unknown Source)
	at java.desktop/sun.font.ExtendedTextSourceLabel.createLogicalBounds(Unknown Source)
	at java.desktop/sun.font.ExtendedTextSourceLabel.getAdvance(Unknown Source)
	at java.desktop/java.awt.font.TextLine.init(Unknown Source)
	at java.desktop/java.awt.font.TextLine.<init>(Unknown Source)
	at java.desktop/java.awt.font.TextLine.fastCreateTextLine(Unknown Source)
	at java.desktop/java.awt.font.TextLayout.fastInit(Unknown Source)
	at java.desktop/java.awt.font.TextLayout.<init>(Unknown Source)
	at biz.ganttproject.core.chart.render.TextLengthCalculatorImpl.getTextLength(TextLengthCalculatorImpl.java:55)
	at biz.ganttproject.core.chart.render.TextLengthCalculatorImpl.getTextLength(TextLengthCalculatorImpl.java:75)
	at biz.ganttproject.core.chart.canvas.Canvas$Text$1.getLabels(Canvas.java:366)
	at biz.ganttproject.core.chart.canvas.Canvas$Text.getLabels(Canvas.java:407)
	at biz.ganttproject.core.chart.render.TextPainter.paint(TextPainter.java:63)
	at net.sourceforge.ganttproject.chart.StyledPainterImpl.paint(StyledPainterImpl.java:371)
	at biz.ganttproject.core.chart.canvas.Canvas.paint(Canvas.java:629)
	at net.sourceforge.ganttproject.chart.ChartModelBase.paint(ChartModelBase.java:430)
	at net.sourceforge.ganttproject.chart.gantt.GanttChartController.paintChart(GanttChartController.java:173)
	at net.sourceforge.ganttproject.ChartComponentBase.paintComponent(ChartComponentBase.java:287)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JLayer.paint(Unknown Source)
	at java.desktop/javax.swing.plaf.LayerUI.paint(Unknown Source)
	at net.sourceforge.ganttproject.AbstractChartImplementation$MouseHoverLayerUi.paint(AbstractChartImplementation.java:91)
	at java.desktop/javax.swing.plaf.ComponentUI.update(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintComponent(Unknown Source)

java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
Oct 16, 2022 1:48:19 AM net.sourceforge.ganttproject.GPLogger log
INFO: [GanttOptions] save(): finished!!

**Comment by dbarashev** [comment]
Can you please share the project file?

**Comment by wcadams55** [comment]
See attached

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by dbarashev** [comment]
Issue tracker on GitHub filters out attachments from email replies. Please attach the project file via GitHub web interface.

**Comment by wcadams55** [comment]
Sorry. Here you go:

[ERP Implementation.zip](https://github.com/bardsoftware/ganttproject/files/9795744/ERP.Implementation.zip)

**Comment by dbarashev** [comment]
Thanks fr reporting. Seems to be a memory leak.
