### ISSUE TITLE
Index out of range upon task deletion

### ISSUE THREAD

**Issue by wcadams55** [bardsoftware/ganttproject#2270]
C:\Users\willa\ganttproject.log

GanttProject 3.2.3247
Settings file:
	location: C:\Users\willa\.ganttproject
	size:6636
	is readable: true
java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject-3.2
java.home: C:\Program Files (x86)\GanttProject-3.2\runtime
java.ext.dirs: null
java.io.tmpdir: C:\Users\willa\AppData\Local\Temp\
java.runtime.version: 11.0.13+8-LTS
java.vendor: BellSoft
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.vendor: BellSoft
java.vm.version: 11.0.13+8-LTS
os.arch: amd64
os.name: Windows 10
os.version: 10.0
sun.java.command: com.bardsoftware.eclipsito.Launch --verbosity 1 --version-dirs plugins;~/.ganttproject.d/updates --app net.sourceforge.ganttproject.GanttProject
user.country: US
user.dir: C:\Program Files (x86)\GanttProject-3.2
user.home: C:\Users\willa
user.language: en
user.timezone: America/New_York

LookAndFeel Plastic(com.jgoodies.looks.plastic.PlasticLookAndFeel) already installed.
Nov 09, 2022 9:19:19 PM biz.ganttproject.LoggerImpl debug
FINE: Creating main frame...
Nov 09, 2022 9:19:19 PM biz.ganttproject.LoggerImpl debug
FINE: 1. loading look'n'feels
Nov 09, 2022 9:19:19 PM biz.ganttproject.LoggerImpl debug
FINE: 2. loading options
Nov 09, 2022 9:19:19 PM biz.ganttproject.LoggerImpl debug
FINE: 3. creating menus...
Nov 09, 2022 9:19:20 PM biz.ganttproject.LoggerImpl debug
FINE: 4. creating views...
Nov 09, 2022 9:19:20 PM biz.ganttproject.LoggerImpl debug
FINE: 5. calculating size and packing...
Nov 09, 2022 9:19:20 PM biz.ganttproject.LoggerImpl debug
FINE: 6. changing language ...
Nov 09, 2022 9:19:20 PM biz.ganttproject.LoggerImpl debug
FINE: 7. first attempt to restore bounds
Nov 09, 2022 9:19:20 PM biz.ganttproject.LoggerImpl debug
FINE: 8. finalizing...
Nov 09, 2022 9:19:20 PM net.sourceforge.ganttproject.GPLogger log
INFO: Deleting old auto-save files
Nov 09, 2022 9:19:40 PM net.sourceforge.ganttproject.GPLogger log
INFO: [GanttOptions] save(): finished!!
Nov 09, 2022 9:19:40 PM net.sourceforge.ganttproject.GPLogger log
INFO: [GanttOptions] save(): finished!!
Nov 09, 2022 9:19:40 PM biz.ganttproject.LoggerImpl error
SEVERE: WebSocket closed. Code=1000, reason=Reset Websocket
Nov 09, 2022 9:19:40 PM biz.ganttproject.LoggerImpl error
SEVERE: WebSocket has been closed
Nov 09, 2022 9:39:32 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: Index 14 out of bounds for length 13
java.lang.ArrayIndexOutOfBoundsException: Index 14 out of bounds for length 13
	at java.base/sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(Unknown Source)
	at java.base/java.util.GregorianCalendar.computeFields(Unknown Source)
	at java.base/java.util.GregorianCalendar.computeFields(Unknown Source)
	at java.base/java.util.Calendar.complete(Unknown Source)
	at java.base/java.util.Calendar.get(Unknown Source)
	at java.base/java.text.SimpleDateFormat.subFormat(Unknown Source)
	at java.base/java.text.SimpleDateFormat.format(Unknown Source)
	at java.base/java.text.SimpleDateFormat.format(Unknown Source)
	at java.base/java.text.DateFormat.format(Unknown Source)
	at net.sourceforge.ganttproject.language.GanttLanguage.formatShortDate(GanttLanguage.java:244)
	at net.sourceforge.ganttproject.AbstractChartImplementation$MouseHoverLayerUi.paint(AbstractChartImplementation.java:111)
	at java.desktop/javax.swing.plaf.ComponentUI.update(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintComponent(Unknown Source)
	at java.desktop/javax.swing.JLayer.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JSplitPane.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JLayeredPane.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JLayer.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.plaf.LayerUI.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JLayer.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

oPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

[ERP Implementation.zip](https://github.com/bardsoftware/ganttproject/files/9975367/ERP.Implementation.zip)

**Comment by dbarashev** [comment]
1. What task one has to delete to reproduce the issue?
2. What is your date format in the settings?
