### ISSUE TITLE
Error when entering a Chinese task title: Index out of bounds and enters an infinite loop

### ISSUE THREAD

**Issue by gjl2011yn** [bardsoftware/ganttproject#2546]
[2024-09-09 08:11:27] [ 警告][net.sourceforge.ganttproject] Index -1 out of bounds for length 26
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 26
at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
at java.base/java.util.Objects.checkIndex(Unknown Source)
at java.base/java.util.ArrayList.get(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateCachedBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.recomputeBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.doComputeGeomBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent$1.doComputeGeomBounds(Unknown Source)
at javafx.graphics/com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(Unknown Source)
at javafx.graphics/com.sun.javafx.scene.NodeHelper.computeGeomBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.updateGeomBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.getGeomBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.getLocalBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.updateTxBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.getTransformedBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)

[2024-09-09 08:11:27] [ 警告][net.sourceforge.ganttproject] Index -1 out of bounds for length 26
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 26
at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
at java.base/java.util.Objects.checkIndex(Unknown Source)
at java.base/java.util.ArrayList.get(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateCachedBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.recomputeBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.doComputeGeomBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent$1.doComputeGeomBounds(Unknown Source)
at javafx.graphics/com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(Unknown Source)
at javafx.graphics/com.sun.javafx.scene.NodeHelper.computeGeomBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.updateGeomBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.getGeomBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.getLocalBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.updateTxBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.getTransformedBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)

[2024-09-09 08:11:27] [ 警告][net.sourceforge.ganttproject] Index -1 out of bounds for length 26
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 26
at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
at java.base/java.util.Objects.checkIndex(Unknown Source)
at java.base/java.util.ArrayList.get(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateCachedBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.recomputeBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.doComputeGeomBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent$1.doComputeGeomBounds(Unknown Source)
at javafx.graphics/com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(Unknown Source)
at javafx.graphics/com.sun.javafx.scene.NodeHelper.computeGeomBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.updateGeomBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.getGeomBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.getLocalBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.updateTxBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.getTransformedBounds(Unknown Source)
at javafx.graphics/javafx.scene.Node.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Parent.updateBounds(Unknown Source)
at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)

**Comment by dbarashev** [comment]
Hello,
please attach _the complete log file_ when this issue happens. The file name is `ganttproject.log`, it sits in your home directory. You may also copy the whole contents shown in Help > View log dialog. What is posted above is a _partial contents_, not the whole.

**Comment by gjl2011yn** [comment]
[Uploading ganttproject.log…]()

**Comment by gjl2011yn** [comment]
[ganttproject.log.zip](https://github.com/user-attachments/files/17144356/ganttproject.log.zip)

**Comment by dbarashev** [comment]
Thanks. Could you also record a video that would show how this issue can be reproduced?
